{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didResume"},{"kind":"text","text":"("},{"kind":"externalParam","text":"upstream"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Upstream","preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream"},{"kind":"text","text":")"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"アップストリーム。"}]}],"name":"upstream"}]}],"sections":[],"metadata":{"title":"didResume(upstream:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didResume"},{"kind":"text","text":"("},{"text":"upstream","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Upstream","preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"iSCP"}],"role":"symbol","externalID":"s:4iSCP16UpstreamDelegateP9didResume8upstreamyAA0B0C_tF","roleHeading":"Instance Method","symbolKind":"method","required":true},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamDelegate\/didResume(upstream:)"},"abstract":[{"type":"text","text":"このストリームの再開処理が成功した際にコールされます。"}],"variants":[{"paths":["\/documentation\/iscp\/upstreamdelegate\/didresume(upstream:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/UpstreamDelegate/didResume(upstream:)":{"title":"didResume(upstream:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didResume"},{"kind":"text","text":"("},{"kind":"externalParam","text":"upstream"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream","text":"Upstream"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"このストリームの再開処理が成功した際にコールされます。"}],"url":"\/documentation\/iscp\/upstreamdelegate\/didresume(upstream:)","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamDelegate\/didResume(upstream:)","required":true},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream":{"navigatorTitle":[{"kind":"identifier","text":"Upstream"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Upstream"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/upstream","kind":"symbol","title":"Upstream","abstract":[{"text":"アップストリームを表すクラスです。","type":"text"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/UpstreamDelegate":{"title":"UpstreamDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpstreamDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"UpstreamDelegate"}],"type":"topic","role":"symbol","abstract":[{"text":"アップストリームで扱われるデリゲートです。","type":"text"}],"url":"\/documentation\/iscp\/upstreamdelegate","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamDelegate"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"type":"topic","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","url":"\/documentation\/iscp","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"Upstream","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/title"},{"value":[{"text":"Upstream","kind":"identifier"}],"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/fragments","op":"replace"},{"value":[{"text":"Upstream","kind":"identifier"}],"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}