{"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Articles","anchor":"Articles","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ConnectToIntdashAPI","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/E2ECall","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/StartDownstream","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/StartUpstream"],"generated":true},{"title":"Classes","anchor":"Classes","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ISCPLog","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/NegotiationParams","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/SequenceNumberGenerator","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Transport","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream"],"generated":true},{"title":"Protocols","anchor":"Protocols","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ConnectionDelegate","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ConnectionE2ECallDelegate","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamDelegate","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/IConnector","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ISCPLogDelegate","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ITransport","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ITransportDelegate","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamDelegate"],"generated":true},{"title":"Structures","anchor":"Structures","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/BaseTime","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataFilter","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataID","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataPoint","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataPointGroup","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamAbnormalClose","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamCall","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamChunk","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamFilter","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamFilterReference","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamFilterReferences","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamMetadata","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamNormalClose","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamOpen","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamReplyCall","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamResume","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/FlushPolicy","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamAbnormalClose","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamCall","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamChunk","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamChunkAck","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamInfo","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamNormalClose","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamOpen","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamReplyCall","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamResume"],"generated":true},{"title":"Variables","anchor":"Variables","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/iscpVersionNumber","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/iscpVersionString","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/kISCPFrameworkVersion","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/kISCPSupportedProtocolVersion"],"generated":true},{"title":"Type Aliases","anchor":"Type-Aliases","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ITransportConfig"],"generated":true},{"title":"Enumerations","anchor":"Enumerations","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/EncodingName","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ISCPError","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ISCPLogLevel","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/QoS","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/SwiftQUICState"],"generated":true},{"title":"Extended Modules","anchor":"Extended-Modules","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Foundation","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Swift"],"generated":true}],"abstract":[{"text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iscp"]}],"sections":[],"primaryContentSections":[{"content":[{"anchor":"Requirements","text":"Requirements","level":2,"type":"heading"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"iOS 13 or later","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"macOS 10.15 (Catalina) or later","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Xcode 26 or later","type":"text"}]}]}]},{"anchor":"Installation","text":"Installation","level":2,"type":"heading"},{"text":"Cocoapods","type":"heading","anchor":"Cocoapods","level":3},{"inlineContent":[{"text":"iscp-swiftは ","type":"text"},{"identifier":"https:\/\/cocoapods.org\/","isActive":true,"type":"reference"},{"text":" から入手可能です。","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":null,"code":["target '{YOUR_APP_SCHEME}' do","  ...","  pod 'iSCP'","  ...","end"]},{"text":"Swift Package Manager","anchor":"Swift-Package-Manager","type":"heading","level":3},{"inlineContent":[{"type":"text","text":"iscp-swiftは "},{"isActive":true,"type":"reference","identifier":"https:\/\/swift.org\/package-manager\/"},{"type":"text","text":" からも利用できます。"}],"type":"paragraph"},{"text":"Third-Party License Notices","anchor":"Third-Party-License-Notices","type":"heading","level":2},{"inlineContent":[{"text":"iscp-swiftはサードパーティ製オープンソースソフトウェアを同梱・利用しています。","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"これらコンポーネントのライセンス条文およびクレジットの詳細は "},{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/aptpod\/iscp-swift\/THIRD-PARTY-LICENSES.txt"},{"type":"text","text":" を参照してください。"}],"type":"paragraph"},{"text":"Dependencies","anchor":"Dependencies","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/apple\/swift-protobuf"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Licensed under the Apache License, Version 2.0."}],"type":"paragraph"}]}]}]}]},{"text":"References","type":"heading","anchor":"References","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"https:\/\/docs.intdash.jp\/api\/intdash-sdk\/swift\/latest\/"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"過去のバージョンのリファレンスは "},{"identifier":"https:\/\/docs.intdash.jp\/api\/intdash-sdk\/swift-versions","type":"reference","isActive":true}],"type":"paragraph"}]}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/aptpod\/iscp-swift"}],"type":"paragraph"}]}]}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP"},"metadata":{"externalID":"iSCP","roleHeading":"Framework","modules":[{"name":"iSCP"}],"role":"collection","symbolKind":"module","title":"iSCP"},"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Foundation":{"kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Foundation","title":"Foundation","url":"\/documentation\/iscp\/foundation","abstract":[],"type":"topic","role":"collection"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/iscpVersionNumber":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iscpVersionNumber","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/iscp\/iscpversionnumber","title":"iscpVersionNumber","kind":"symbol","type":"topic","navigatorTitle":[{"text":"iscpVersionNumber","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/iscpVersionNumber","abstract":[{"type":"text","text":"Project version number for iscp."}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/iscpVersionString":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iscpVersionString","kind":"identifier"},{"text":": _","kind":"text"}],"navigatorTitle":[{"text":"iscpVersionString","kind":"identifier"}],"kind":"symbol","title":"iscpVersionString","role":"symbol","url":"\/documentation\/iscp\/iscpversionstring","abstract":[{"type":"text","text":"Project version string for iscp"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/iscpVersionString","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/SequenceNumberGenerator":{"kind":"symbol","title":"SequenceNumberGenerator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SequenceNumberGenerator","kind":"identifier"}],"navigatorTitle":[{"text":"SequenceNumberGenerator","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"シーケンス番号を生成することができるクラスです。"}],"url":"\/documentation\/iscp\/sequencenumbergenerator","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/SequenceNumberGenerator"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DownstreamCall":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownstreamCall"}],"navigatorTitle":[{"kind":"identifier","text":"DownstreamCall"}],"title":"DownstreamCall","kind":"symbol","role":"symbol","url":"\/documentation\/iscp\/downstreamcall","abstract":[{"type":"text","text":"ダウンストリームコールです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamCall","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DownstreamMetadata":{"type":"topic","abstract":[{"type":"text","text":"ダウンストリームメタデータです。"}],"navigatorTitle":[{"kind":"identifier","text":"DownstreamMetadata"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownstreamMetadata"}],"kind":"symbol","url":"\/documentation\/iscp\/downstreammetadata","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamMetadata","title":"DownstreamMetadata"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/ConnectionE2ECallDelegate":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionE2ECallDelegate"}],"url":"\/documentation\/iscp\/connectione2ecalldelegate","title":"ConnectionE2ECallDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionE2ECallDelegate"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ConnectionE2ECallDelegate","abstract":[{"type":"text","text":"コネクションで発生するE2Eコールのデリゲートです。"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DataPointGroup":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataPointGroup"}],"role":"symbol","url":"\/documentation\/iscp\/datapointgroup","title":"DataPointGroup","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"ストリームチャンクの中のデータポイントをデータIDごとにまとめた集合です。"}],"navigatorTitle":[{"kind":"identifier","text":"DataPointGroup"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataPointGroup"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/ConnectToIntdashAPI":{"role":"article","url":"\/documentation\/iscp\/connecttointdashapi","kind":"article","type":"topic","title":"Connect To intdash API","abstract":[{"type":"text","text":"このサンプルではiscp-swiftを使ってintdash APIに接続します。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ConnectToIntdashAPI"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/QoS":{"title":"QoS","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"QoS","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"QoS"}],"type":"topic","role":"symbol","abstract":[{"type":"codeVoice","code":"QoS"},{"type":"text","text":" を表します。"}],"url":"\/documentation\/iscp\/qos","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/QoS"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DownstreamReplyCall":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DownstreamReplyCall","kind":"identifier"}],"navigatorTitle":[{"text":"DownstreamReplyCall","kind":"identifier"}],"kind":"symbol","title":"DownstreamReplyCall","role":"symbol","url":"\/documentation\/iscp\/downstreamreplycall","abstract":[{"type":"text","text":"ダウンストリームリプライコールです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamReplyCall","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/NegotiationParams":{"navigatorTitle":[{"text":"NegotiationParams","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/NegotiationParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NegotiationParams"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/negotiationparams","title":"NegotiationParams","abstract":[{"type":"text","text":"ネゴシエーションパラメータです。"}],"kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DownstreamDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownstreamDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"DownstreamDelegate"}],"title":"DownstreamDelegate","kind":"symbol","role":"symbol","url":"\/documentation\/iscp\/downstreamdelegate","abstract":[{"text":"ダウンストリームで扱われるデリゲートです。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamDelegate","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/FlushPolicy":{"type":"topic","abstract":[{"code":"Upstream","type":"codeVoice"},{"type":"text","text":" のフラッシュの方法について定義します。"}],"navigatorTitle":[{"kind":"identifier","text":"FlushPolicy"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"FlushPolicy","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/iscp\/flushpolicy","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/FlushPolicy","title":"FlushPolicy"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/E2ECall":{"role":"article","url":"\/documentation\/iscp\/e2ecall","kind":"article","type":"topic","title":"E2E Call","abstract":[{"type":"text","text":"E2E（エンドツーエンド）コールのサンプルです。コントローラーノードが対象ノードに対して指示を出し、対象ノードは受信完了のリプライを行う簡単なサンプルです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/E2ECall"},"https://github.com/aptpod/iscp-swift/THIRD-PARTY-LICENSES.txt":{"url":"https:\/\/github.com\/aptpod\/iscp-swift\/THIRD-PARTY-LICENSES.txt","identifier":"https:\/\/github.com\/aptpod\/iscp-swift\/THIRD-PARTY-LICENSES.txt","type":"link","title":"THIRD-PARTY-LICENSES.txt","titleInlineContent":[{"type":"text","text":"THIRD-PARTY-LICENSES.txt"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DownstreamFilter":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DownstreamFilter","kind":"identifier"}],"role":"symbol","url":"\/documentation\/iscp\/downstreamfilter","title":"DownstreamFilter","type":"topic","kind":"symbol","abstract":[{"text":"ダウンストリームフィルタです。","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DownstreamFilter"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamFilter"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Transport":{"kind":"symbol","navigatorTitle":[{"text":"Transport","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Transport"}],"abstract":[{"type":"text","text":"iSCPのトランスポートです。"}],"url":"\/documentation\/iscp\/transport","title":"Transport","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Transport"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Swift":{"type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Swift","url":"\/documentation\/iscp\/swift","title":"Swift","kind":"symbol","role":"collection","abstract":[]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/IConnector":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IConnector"}],"navigatorTitle":[{"kind":"identifier","text":"IConnector"}],"title":"IConnector","kind":"symbol","role":"symbol","url":"\/documentation\/iscp\/iconnector","abstract":[{"type":"text","text":"iSCPコネクターのインターフェースです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/IConnector","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/StartDownstream":{"role":"article","url":"\/documentation\/iscp\/startdownstream","title":"Start Downstream","type":"topic","kind":"article","abstract":[{"type":"text","text":"アップストリームで送信されたデータをダウンストリームで受信するサンプルです。このサンプルでは、アップストリーム開始のメタデータ、基準時刻のメタデータ、 文字列型のデータポイントを受信しています。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/StartDownstream"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/UpstreamDelegate":{"title":"UpstreamDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpstreamDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"UpstreamDelegate"}],"type":"topic","role":"symbol","abstract":[{"text":"アップストリームで扱われるデリゲートです。","type":"text"}],"url":"\/documentation\/iscp\/upstreamdelegate","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamDelegate"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DownstreamOpen":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DownstreamOpen","kind":"identifier"}],"url":"\/documentation\/iscp\/downstreamopen","title":"DownstreamOpen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DownstreamOpen"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamOpen","abstract":[{"text":"あるダウンストリームが開いたことを知らせるメタデータです。","type":"text"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DownstreamChunk":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownstreamChunk"}],"role":"symbol","url":"\/documentation\/iscp\/downstreamchunk","title":"DownstreamChunk","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"ダウンストリームチャンクを表します。"}],"navigatorTitle":[{"kind":"identifier","text":"DownstreamChunk"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamChunk"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/EncodingName":{"kind":"symbol","title":"EncodingName","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EncodingName","kind":"identifier"}],"navigatorTitle":[{"text":"EncodingName","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"エンコーディングの名前です。"}],"url":"\/documentation\/iscp\/encodingname","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/EncodingName"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DataID":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DataID","kind":"identifier"}],"navigatorTitle":[{"text":"DataID","kind":"identifier"}],"kind":"symbol","title":"DataID","role":"symbol","url":"\/documentation\/iscp\/dataid","abstract":[{"type":"text","text":"データポイントの、名称とデータ型を表す識別子です。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataID","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/UpstreamReplyCall":{"type":"topic","title":"UpstreamReplyCall","abstract":[{"type":"text","text":"アップストリームリプライコールです。"}],"url":"\/documentation\/iscp\/upstreamreplycall","role":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamReplyCall","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpstreamReplyCall"}],"navigatorTitle":[{"kind":"identifier","text":"UpstreamReplyCall"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/kISCPFrameworkVersion":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kISCPFrameworkVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/iscp\/kiscpframeworkversion","title":"kISCPFrameworkVersion","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"このフレームワークのバージョン。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/kISCPFrameworkVersion"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/ISCPLogLevel":{"navigatorTitle":[{"text":"ISCPLogLevel","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ISCPLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ISCPLogLevel","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/iscploglevel","title":"ISCPLogLevel","abstract":[{"text":"ログレベルを表す列挙型。","type":"text"}],"kind":"symbol"},"https://github.com/aptpod/iscp-swift":{"url":"https:\/\/github.com\/aptpod\/iscp-swift","identifier":"https:\/\/github.com\/aptpod\/iscp-swift","type":"link","title":"GitHub","titleInlineContent":[{"type":"text","text":"GitHub"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DownstreamAbnormalClose":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DownstreamAbnormalClose","kind":"identifier"}],"role":"symbol","url":"\/documentation\/iscp\/downstreamabnormalclose","title":"DownstreamAbnormalClose","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"あるダウンストリームが異常切断したことを知らせるメタデータです。"}],"navigatorTitle":[{"text":"DownstreamAbnormalClose","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamAbnormalClose"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/UpstreamChunk":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpstreamChunk"}],"url":"\/documentation\/iscp\/upstreamchunk","title":"UpstreamChunk","kind":"symbol","type":"topic","navigatorTitle":[{"text":"UpstreamChunk","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamChunk","abstract":[{"text":"アップストリームチャンクを表します。","type":"text"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/UpstreamResume":{"type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamResume","title":"UpstreamResume","url":"\/documentation\/iscp\/upstreamresume","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpstreamResume"}],"abstract":[{"type":"text","text":"あるアップストリームが再開したことを知らせるメタデータです。"}],"navigatorTitle":[{"kind":"identifier","text":"UpstreamResume"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/ITransportDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ITransportDelegate"}],"role":"symbol","url":"\/documentation\/iscp\/itransportdelegate","title":"ITransportDelegate","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"トランスポートの処理イベントです。"}],"navigatorTitle":[{"kind":"identifier","text":"ITransportDelegate"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ITransportDelegate"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/ISCPLogDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ISCPLogDelegate"}],"role":"symbol","url":"\/documentation\/iscp\/iscplogdelegate","title":"ISCPLogDelegate","type":"topic","kind":"symbol","abstract":[{"text":"出力するログをハンドリングすることができるデリゲートです。","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ISCPLogDelegate"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ISCPLogDelegate"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/UpstreamNormalClose":{"navigatorTitle":[{"text":"UpstreamNormalClose","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamNormalClose","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UpstreamNormalClose","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/upstreamnormalclose","kind":"symbol","abstract":[{"type":"text","text":"あるアップストリームが正常切断したことを知らせるメタデータです。"}],"title":"UpstreamNormalClose"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/ITransportConfig":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ITransportConfig","kind":"identifier"}],"role":"symbol","url":"\/documentation\/iscp\/itransportconfig","title":"ITransportConfig","type":"topic","kind":"symbol","deprecated":true,"abstract":[],"navigatorTitle":[{"text":"ITransportConfig","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ITransportConfig"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DownstreamFilterReference":{"title":"DownstreamFilterReference","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownstreamFilterReference"}],"navigatorTitle":[{"kind":"identifier","text":"DownstreamFilterReference"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"ダウンストリームフィルタリファレンス。"}],"url":"\/documentation\/iscp\/downstreamfilterreference","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamFilterReference"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/SwiftQUICState":{"navigatorTitle":[{"kind":"identifier","text":"SwiftQUICState"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/SwiftQUICState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwiftQUICState"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/swiftquicstate","title":"SwiftQUICState","abstract":[],"kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/ConnectionDelegate":{"type":"topic","abstract":[{"type":"text","text":"コネクションで扱われるデリゲートです。"}],"navigatorTitle":[{"kind":"identifier","text":"ConnectionDelegate"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/iscp\/connectiondelegate","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ConnectionDelegate","title":"ConnectionDelegate"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/BaseTime":{"navigatorTitle":[{"kind":"identifier","text":"BaseTime"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/BaseTime","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTime"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/basetime","title":"BaseTime","abstract":[{"type":"text","text":"基準時刻です。"}],"kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DownstreamNormalClose":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownstreamNormalClose"}],"navigatorTitle":[{"kind":"identifier","text":"DownstreamNormalClose"}],"title":"DownstreamNormalClose","kind":"symbol","role":"symbol","url":"\/documentation\/iscp\/downstreamnormalclose","abstract":[{"text":"あるダウンストリームが正常切断したことを知らせるメタデータです。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamNormalClose","type":"topic"},"https://cocoapods.org/":{"url":"https:\/\/cocoapods.org\/","identifier":"https:\/\/cocoapods.org\/","type":"link","title":"CocoaPods","titleInlineContent":[{"type":"text","text":"CocoaPods"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/ISCPError":{"kind":"symbol","title":"ISCPError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ISCPError","kind":"identifier"}],"navigatorTitle":[{"text":"ISCPError","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"iscp-swift内部で発生するエラーの定義です。"}],"url":"\/documentation\/iscp\/iscperror","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ISCPError"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DataFilter":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataFilter"}],"navigatorTitle":[{"kind":"identifier","text":"DataFilter"}],"title":"DataFilter","kind":"symbol","role":"symbol","url":"\/documentation\/iscp\/datafilter","abstract":[{"type":"text","text":"受信するデータを指定するためのデータフィルタです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataFilter","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/StartUpstream":{"role":"article","url":"\/documentation\/iscp\/startupstream","title":"Start Upstream","type":"topic","kind":"article","abstract":[{"type":"text","text":"アップストリームの送信サンプルです。このサンプルでは、基準時刻のメタデータと、文字列型のデータポイントをiSCPサーバーへ送信しています。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/StartUpstream"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DownstreamFilterReferences":{"kind":"symbol","title":"DownstreamFilterReferences","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DownstreamFilterReferences","kind":"identifier"}],"navigatorTitle":[{"text":"DownstreamFilterReferences","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"ダウンストリームフィルタリファレンス。"}],"url":"\/documentation\/iscp\/downstreamfilterreferences","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamFilterReferences"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/UpstreamChunkAck":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpstreamChunkAck"}],"url":"\/documentation\/iscp\/upstreamchunkack","title":"UpstreamChunkAck","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UpstreamChunkAck"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamChunkAck","abstract":[{"text":"アップストリームチャンクに対する確認応答です。","type":"text"}]},"https://swift.org/package-manager/":{"url":"https:\/\/swift.org\/package-manager\/","identifier":"https:\/\/swift.org\/package-manager\/","type":"link","title":"Swift Package Manager","titleInlineContent":[{"type":"text","text":"Swift Package Manager"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection":{"navigatorTitle":[{"kind":"identifier","text":"Connection"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Connection"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/connection","title":"Connection","abstract":[{"type":"text","text":"iSCPのコネクションを表すクラスです。"}],"kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/UpstreamInfo":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpstreamInfo"}],"navigatorTitle":[{"kind":"identifier","text":"UpstreamInfo"}],"kind":"symbol","title":"UpstreamInfo","role":"symbol","url":"\/documentation\/iscp\/upstreaminfo","abstract":[{"type":"text","text":"アップストリーム情報。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamInfo","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/ISCPLog":{"navigatorTitle":[{"text":"ISCPLog","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ISCPLog","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ISCPLog","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/iscplog","title":"ISCPLog","abstract":[{"type":"text","text":"iscp-swift内のログ出力クラスです。"}],"kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/UpstreamOpen":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UpstreamOpen","kind":"identifier"}],"role":"symbol","url":"\/documentation\/iscp\/upstreamopen","kind":"symbol","title":"UpstreamOpen","type":"topic","abstract":[{"type":"text","text":"あるアップストリームが開いたことを知らせるメタデータです。"}],"navigatorTitle":[{"text":"UpstreamOpen","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamOpen"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream":{"title":"Downstream","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Downstream"}],"navigatorTitle":[{"kind":"identifier","text":"Downstream"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"ダウンストリームを表すクラスです。"}],"url":"\/documentation\/iscp\/downstream","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/kISCPSupportedProtocolVersion":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kISCPSupportedProtocolVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/iscp\/kiscpsupportedprotocolversion","title":"kISCPSupportedProtocolVersion","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"対応しているプロトコルバージョン。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/kISCPSupportedProtocolVersion"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream":{"navigatorTitle":[{"kind":"identifier","text":"Upstream"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Upstream"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/upstream","kind":"symbol","title":"Upstream","abstract":[{"text":"アップストリームを表すクラスです。","type":"text"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DownstreamResume":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownstreamResume"}],"navigatorTitle":[{"kind":"identifier","text":"DownstreamResume"}],"title":"DownstreamResume","kind":"symbol","role":"symbol","url":"\/documentation\/iscp\/downstreamresume","abstract":[{"type":"text","text":"あるダウンストリームが再開したことを知らせるメタデータです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamResume","type":"topic"},"https://docs.intdash.jp/api/intdash-sdk/swift-versions":{"url":"https:\/\/docs.intdash.jp\/api\/intdash-sdk\/swift-versions","identifier":"https:\/\/docs.intdash.jp\/api\/intdash-sdk\/swift-versions","type":"link","title":"こちら","titleInlineContent":[{"type":"text","text":"こちら"}]},"https://github.com/apple/swift-protobuf":{"url":"https:\/\/github.com\/apple\/swift-protobuf","identifier":"https:\/\/github.com\/apple\/swift-protobuf","type":"link","title":"SwiftProtobuf","titleInlineContent":[{"type":"text","text":"SwiftProtobuf"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/UpstreamCall":{"kind":"symbol","title":"UpstreamCall","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UpstreamCall","kind":"identifier"}],"navigatorTitle":[{"text":"UpstreamCall","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"アップストリームコールです。"}],"url":"\/documentation\/iscp\/upstreamcall","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamCall"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"type":"topic","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","url":"\/documentation\/iscp","kind":"symbol","role":"collection"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/ITransport":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ITransport","kind":"identifier"}],"navigatorTitle":[{"text":"ITransport","kind":"identifier"}],"kind":"symbol","title":"ITransport","role":"symbol","url":"\/documentation\/iscp\/itransport","abstract":[{"type":"text","text":"トランスポートを管理する基底インターフェースです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ITransport","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/UpstreamAbnormalClose":{"kind":"symbol","navigatorTitle":[{"text":"UpstreamAbnormalClose","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UpstreamAbnormalClose","kind":"identifier"}],"abstract":[{"type":"text","text":"あるアップストリームが異常切断したことを知らせるメタデータです。"}],"url":"\/documentation\/iscp\/upstreamabnormalclose","title":"UpstreamAbnormalClose","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamAbnormalClose"},"https://docs.intdash.jp/api/intdash-sdk/swift/latest/":{"url":"https:\/\/docs.intdash.jp\/api\/intdash-sdk\/swift\/latest\/","identifier":"https:\/\/docs.intdash.jp\/api\/intdash-sdk\/swift\/latest\/","type":"link","title":"APIリファレンス","titleInlineContent":[{"type":"text","text":"APIリファレンス"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DataPoint":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DataPoint"}],"role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataPoint","kind":"identifier"}],"abstract":[{"type":"text","text":"データポイントです。"}],"url":"\/documentation\/iscp\/datapoint","title":"DataPoint","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataPoint"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"title":"Articles","anchor":"Articles","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ConnectToIntdashAPI","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/E2ECall","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/StartDownstream","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/StartUpstream"]},{"title":"Classes","anchor":"Classes","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream"]},{"title":"Variables","anchor":"Variables","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/iscpVersionNumber","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/iscpVersionString"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"iscpVersionNumber","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1iscpVersionNumber\/title"},{"value":[{"kind":"identifier","text":"iscpVersionNumber"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1iscpVersionNumber\/fragments"},{"value":"iscpVersionString","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1iscpVersionString\/title"},{"value":[{"kind":"identifier","text":"iscpVersionString"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1iscpVersionString\/fragments"},{"value":"Connection","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/title"},{"value":[{"kind":"identifier","text":"Connection"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/fragments"},{"value":[{"kind":"identifier","text":"Connection"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/navigatorTitle"},{"value":"Downstream","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/title"},{"value":[{"kind":"identifier","text":"Downstream"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/fragments"},{"value":[{"kind":"identifier","text":"Downstream"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/navigatorTitle"},{"value":"Upstream","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/title"},{"value":[{"kind":"identifier","text":"Upstream"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/fragments"},{"value":[{"kind":"identifier","text":"Upstream"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/navigatorTitle"}]}]}