{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscp\/connection\/default_connect_timeout"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_CONNECT_TIMEOUT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"role":"symbol","title":"DEFAULT_CONNECT_TIMEOUT","modules":[{"name":"iSCP"}],"externalID":"s:4iSCP10ConnectionC23DEFAULT_CONNECT_TIMEOUTSdvpZ","roleHeading":"Type Property","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"コネクトのタイムアウトのデフォルト値。"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_CONNECT_TIMEOUT"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_CONNECT_TIMEOUT"},"sections":[],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"type":"topic","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","url":"\/documentation\/iscp","kind":"symbol","role":"collection"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/DEFAULT_CONNECT_TIMEOUT":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_CONNECT_TIMEOUT"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"role":"symbol","url":"\/documentation\/iscp\/connection\/default_connect_timeout","title":"DEFAULT_CONNECT_TIMEOUT","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"コネクトのタイムアウトのデフォルト値。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_CONNECT_TIMEOUT"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection":{"navigatorTitle":[{"kind":"identifier","text":"Connection"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Connection"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/connection","title":"Connection","abstract":[{"type":"text","text":"iSCPのコネクションを表すクラスです。"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Connection","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/title"},{"value":[{"kind":"identifier","text":"Connection"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/fragments"},{"value":[{"kind":"identifier","text":"Connection"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/navigatorTitle"}]}]}