{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/didConnect(_:)","interfaceLanguage":"swift"},"metadata":{"extendedModule":"iSCP","symbolKind":"method","externalID":"s:4iSCP10ConnectionC10didConnectyyAA10ITransport_pF","modules":[{"name":"iSCP"}],"roleHeading":"Instance Method","role":"symbol","title":"didConnect(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didConnect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP10ITransportP","text":"ITransport"},{"kind":"text","text":")"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscp\/connection\/didconnect(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/ITransportDelegate-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didConnect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"transport","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ITransport","preciseIdentifier":"s:4iSCP10ITransportP","text":"ITransport","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"サーバーとの接続に成功した際にコールしてください。"}],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","title":"Connection","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Connection","kind":"identifier"}],"navigatorTitle":[{"text":"Connection","kind":"identifier"}],"abstract":[{"text":"iSCPのコネクションを表すクラスです。","type":"text"}],"url":"\/documentation\/iscp\/connection","role":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/didConnect(_:)":{"role":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/didConnect(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didConnect"},{"kind":"text","text":"("},{"preciseIdentifier":"s:4iSCP10ITransportP","kind":"typeIdentifier","text":"ITransport"},{"kind":"text","text":")"}],"url":"\/documentation\/iscp\/connection\/didconnect(_:)","type":"topic","abstract":[{"text":"サーバーとの接続に成功した際にコールしてください。","type":"text"}],"kind":"symbol","title":"didConnect(_:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"title":"iSCP","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","url":"\/documentation\/iscp","type":"topic","kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/ITransport":{"role":"symbol","title":"ITransport","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ITransport"}],"kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ITransport","url":"\/documentation\/iscp\/itransport","navigatorTitle":[{"text":"ITransport","kind":"identifier"}],"abstract":[{"type":"text","text":"トランスポートを管理する基底インターフェースです。"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/ITransportDelegate-Implementations":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/ITransportDelegate-Implementations","url":"\/documentation\/iscp\/connection\/itransportdelegate-implementations","type":"topic","abstract":[],"kind":"article","title":"ITransportDelegate Implementations","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/title","op":"replace","value":"Connection"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/fragments","op":"replace","value":[{"kind":"identifier","text":"Connection"}]},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Connection"}]}]}]}