{"kind":"symbol","abstract":[{"type":"text","text":"ダウンストリームを開きます。"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openDownstream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"downstreamFilters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP16DownstreamFilterV","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamFilter","text":"DownstreamFilter"},{"kind":"text","text":"] = [], "},{"kind":"externalParam","text":"dataIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP6DataIDV","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataID","text":"DataID"},{"kind":"text","text":"] = [], "},{"kind":"externalParam","text":"qos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP3QoSO","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/QoS","text":"QoS"},{"kind":"text","text":" = Downstream.DEFAULT_QOS, "},{"kind":"externalParam","text":"omitEmptyChunk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = Downstream.DEFAULT_OMIT_EMPTY_CHUNK, "},{"kind":"externalParam","text":"expiryInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":" = Downstream.DEFAULT_EXPIRY_INTERVAL, "},{"kind":"externalParam","text":"ackInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":" = Downstream.DEFAULT_ACK_INTERVAL, "},{"kind":"externalParam","text":"openTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":" = Downstream.DEFAULT_OPEN_TIMEOUT, "},{"kind":"externalParam","text":"closeTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":" = Downstream.DEFAULT_CLOSE_TIMEOUT, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"downstream"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@iSCP@objc(cs)Downstream","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","text":"Downstream"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> ()))"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"ダウンストリームフィルター。","type":"text"}]}],"name":"downstreamFilters"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"エイリアスを設定するデータIDのリスト。"}]}],"name":"dataIDs"},{"content":[{"inlineContent":[{"text":"QoS。現在は ","type":"text"},{"type":"codeVoice","code":"unreliable"},{"text":" のみサポート。","type":"text"}],"type":"paragraph"}],"name":"qos"},{"content":[{"inlineContent":[{"type":"text","text":"空チャンク省略フラグ。trueの場合、DownstreamChunk内のdataPointGroupsが空の時、DownstreamChunkの送信を省略します。"}],"type":"paragraph"}],"name":"omitEmptyChunk"},{"content":[{"type":"paragraph","inlineContent":[{"text":"有効期限。このストリームが異常切断された時点からの有効期限を表します。最小値の ","type":"text"},{"code":"0","type":"codeVoice"},{"text":" は、異常切断されたと同時に有効期限切れとなることを表します。","type":"text"}]}],"name":"expiryInterval"},{"content":[{"inlineContent":[{"type":"text","text":"Ack返却間隔。受信したメッセージに対するAckの返却間隔です。"}],"type":"paragraph"}],"name":"ackInterval"},{"content":[{"inlineContent":[{"text":"オープンのタイムアウト。 ","type":"text"},{"code":"0","type":"codeVoice"},{"text":" 以下の場合はタイムアウトしません。","type":"text"}],"type":"paragraph"}],"name":"openTimeout"},{"content":[{"type":"paragraph","inlineContent":[{"text":"クローズのタイムアウト。 ","type":"text"},{"type":"codeVoice","code":"0"},{"text":" 以下の場合はタイムアウトしません。","type":"text"}]}],"name":"closeTimeout"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"処理完了時のコールバック。"}]}],"name":"completion"}],"kind":"parameters"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openDownstream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"downstreamFilters","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DownstreamFilter","preciseIdentifier":"s:4iSCP16DownstreamFilterV","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"dataIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DataID","preciseIdentifier":"s:4iSCP6DataIDV","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"qos","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"QoS","preciseIdentifier":"s:4iSCP3QoSO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"omitEmptyChunk","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expiryInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ackInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"openTimeout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"closeTimeout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"downstream","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Downstream","preciseIdentifier":"c:@M@iSCP@objc(cs)Downstream","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ()))","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"iSCP"}],"extendedModule":"iSCP","externalID":"s:4iSCP10ConnectionC14openDownstream17downstreamFilters7dataIDs3qos14omitEmptyChunk14expiryInterval03ackN00C7Timeout05closeP010completionySayAA0D6FilterVG_SayAA6DataIDVGAA3QoSOSbS4dyAA0D0CSg_s5Error_pSgtctF","symbolKind":"method","role":"symbol","title":"openDownstream(downstreamFilters:dataIDs:qos:omitEmptyChunk:expiryInterval:ackInterval:openTimeout:closeTimeout:completion:)"},"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection"]]},"identifier":{"url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/openDownstream(downstreamFilters:dataIDs:qos:omitEmptyChunk:expiryInterval:ackInterval:openTimeout:closeTimeout:completion:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/iscp\/connection\/opendownstream(downstreamfilters:dataids:qos:omitemptychunk:expiryinterval:ackinterval:opentimeout:closetimeout:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/QoS":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/QoS","title":"QoS","abstract":[{"type":"text","text":"QoSを表します。"}],"navigatorTitle":[{"kind":"identifier","text":"QoS"}],"url":"\/documentation\/iscp\/qos","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"QoS"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DataID":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataID","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"DataID","kind":"identifier"}],"abstract":[{"text":"データポイントの、名称とデータ型を表す識別子です。","type":"text"}],"url":"\/documentation\/iscp\/dataid","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataID","kind":"identifier"}],"title":"DataID"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"title":"iSCP","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","url":"\/documentation\/iscp","type":"topic","kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","title":"Connection","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Connection","kind":"identifier"}],"navigatorTitle":[{"text":"Connection","kind":"identifier"}],"abstract":[{"text":"iSCPのコネクションを表すクラスです。","type":"text"}],"url":"\/documentation\/iscp\/connection","role":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","role":"symbol","url":"\/documentation\/iscp\/downstream","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Downstream","kind":"identifier"}],"title":"Downstream","kind":"symbol","abstract":[{"type":"text","text":"ダウンストリームを表すクラスです。"}],"navigatorTitle":[{"text":"Downstream","kind":"identifier"}],"type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DownstreamFilter":{"navigatorTitle":[{"text":"DownstreamFilter","kind":"identifier"}],"type":"topic","abstract":[{"text":"ダウンストリームフィルタです。","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DownstreamFilter","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/iscp\/downstreamfilter","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamFilter","role":"symbol","title":"DownstreamFilter"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/openDownstream(downstreamFilters:dataIDs:qos:omitEmptyChunk:expiryInterval:ackInterval:openTimeout:closeTimeout:completion:)":{"abstract":[{"text":"ダウンストリームを開きます。","type":"text"}],"url":"\/documentation\/iscp\/connection\/opendownstream(downstreamfilters:dataids:qos:omitemptychunk:expiryinterval:ackinterval:opentimeout:closetimeout:completion:)","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/openDownstream(downstreamFilters:dataIDs:qos:omitEmptyChunk:expiryInterval:ackInterval:openTimeout:closeTimeout:completion:)","title":"openDownstream(downstreamFilters:dataIDs:qos:omitEmptyChunk:expiryInterval:ackInterval:openTimeout:closeTimeout:completion:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openDownstream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"downstreamFilters","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:4iSCP16DownstreamFilterV","text":"DownstreamFilter","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"dataIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:4iSCP6DataIDV","text":"DataID","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"qos","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:4iSCP3QoSO","text":"QoS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"omitEmptyChunk","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expiryInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ackInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"openTimeout","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"closeTimeout","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"downstream","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@iSCP@objc(cs)Downstream","text":"Downstream","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ()))","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/title","op":"replace","value":"Connection"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/fragments","op":"replace","value":[{"kind":"identifier","text":"Connection"}]},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/navigatorTitle","op":"replace","value":[{"text":"Connection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/title","op":"replace","value":"Downstream"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/fragments","op":"replace","value":[{"kind":"identifier","text":"Downstream"}]},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/navigatorTitle","op":"replace","value":[{"text":"Downstream","kind":"identifier"}]}]}]}