{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openUpstream","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expiryInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":" = Upstream.DEFAULT_EXPIRY_INTERVAL, ","kind":"text"},{"text":"dataIDs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DataID","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataID","preciseIdentifier":"s:4iSCP6DataIDV","kind":"typeIdentifier"},{"text":"] = [], ","kind":"text"},{"kind":"externalParam","text":"qos"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/QoS","preciseIdentifier":"s:4iSCP3QoSO","text":"QoS","kind":"typeIdentifier"},{"text":" = Upstream.DEFAULT_QOS, ","kind":"text"},{"kind":"externalParam","text":"ackInterval"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" = Upstream.DEFAULT_ACK_INTERVAL, ","kind":"text"},{"text":"persist","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = Upstream.DEFAULT_PERSIST, ","kind":"text"},{"text":"flushPolicy","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FlushPolicy","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/FlushPolicy","preciseIdentifier":"s:4iSCP11FlushPolicyV"},{"kind":"text","text":" = Upstream.DEFAULT_FLUSH_POLICY, "},{"text":"closeTimeout","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":" = Upstream.DEFAULT_CLOSE_TIMEOUT, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"upstream","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Upstream","preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream","kind":"typeIdentifier","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ()))"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"sessionID","content":[{"type":"paragraph","inlineContent":[{"text":"セッションID。","type":"text"}]}]},{"name":"expiryInterval","content":[{"inlineContent":[{"type":"text","text":"有効期限。このストリームが異常切断された時点からの有効期限を表します。最小値の "},{"type":"codeVoice","code":"0"},{"text":" は、異常切断されたと同時に有効期限切れとなることを表します。","type":"text"}],"type":"paragraph"}]},{"name":"dataIDs","content":[{"type":"paragraph","inlineContent":[{"text":"送信予定のデータIDのリスト。送信されるデータのデータIDが ","type":"text"},{"code":"dataIDs","type":"codeVoice"},{"type":"text","text":" に含まれていなかった場合、自動的にそのデータIDが "},{"code":"dataIDs","type":"codeVoice"},{"text":" に追加されます（そのため、","type":"text"},{"type":"codeVoice","code":"dataIDs"},{"type":"text","text":" に空のリストが設定されていても問題ありません）。"}]}]},{"name":"qos","content":[{"type":"paragraph","inlineContent":[{"text":"QoS。現在は ","type":"text"},{"type":"codeVoice","code":"unreliable"},{"text":" のみサポート。","type":"text"}]}]},{"name":"ackInterval","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Ack返却間隔。このストリームで送信されたデータに対する確認応答の間隔を表します。"},{"type":"codeVoice","code":"0"},{"type":"text","text":" が設定された場合、ブローカーは1つの "},{"code":"UpstreamChunk","type":"codeVoice"},{"text":" メッセージごとに 1つの ","type":"text"},{"type":"codeVoice","code":"UpstreamChunkAck"},{"text":" メッセージを返却します。","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"永続化するかどうか。"}],"type":"paragraph"}],"name":"persist"},{"content":[{"inlineContent":[{"type":"text","text":"データポイントのフラッシュポリシー。"}],"type":"paragraph"}],"name":"flushPolicy"},{"content":[{"type":"paragraph","inlineContent":[{"text":"クローズのタイムアウト。","type":"text"}]}],"name":"closeTimeout"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"処理完了時のコールバック。","type":"text"}]}]}],"kind":"parameters"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/openUpstream(sessionID:expiryInterval:dataIDs:qos:ackInterval:persist:flushPolicy:closeTimeout:completion:)"},"abstract":[{"type":"text","text":"アップストリームを開きます。"}],"variants":[{"paths":["\/documentation\/iscp\/connection\/openupstream(sessionid:expiryinterval:dataids:qos:ackinterval:persist:flushpolicy:closetimeout:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openUpstream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sessionID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"expiryInterval","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"text":"dataIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DataID","preciseIdentifier":"s:4iSCP6DataIDV","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"qos","kind":"externalParam"},{"kind":"text","text":": "},{"text":"QoS","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP3QoSO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ackInterval"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"persist"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"flushPolicy","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4iSCP11FlushPolicyV","text":"FlushPolicy","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"closeTimeout"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"upstream"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Upstream","preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ()))"}],"externalID":"s:4iSCP10ConnectionC12openUpstream9sessionID14expiryInterval7dataIDs3qos03ackH07persist11flushPolicy12closeTimeout10completionySS_SdSayAA04DataF0VGAA3QoSOSdSbAA05FlushO0VSdyAA0D0CSg_s5Error_pSgtctF","symbolKind":"method","title":"openUpstream(sessionID:expiryInterval:dataIDs:qos:ackInterval:persist:flushPolicy:closeTimeout:completion:)","modules":[{"name":"iSCP"}],"role":"symbol","roleHeading":"Instance Method","extendedModule":"iSCP"},"sections":[],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/openUpstream(sessionID:expiryInterval:dataIDs:qos:ackInterval:persist:flushPolicy:closeTimeout:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"openUpstream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionID"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"expiryInterval"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dataIDs"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:4iSCP6DataIDV","kind":"typeIdentifier","text":"DataID"},{"text":"], ","kind":"text"},{"text":"qos","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP3QoSO","text":"QoS"},{"kind":"text","text":", "},{"text":"ackInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"persist","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"flushPolicy","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FlushPolicy","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP11FlushPolicyV"},{"kind":"text","text":", "},{"text":"closeTimeout","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"upstream","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Upstream","kind":"typeIdentifier","preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ()))","kind":"text"}],"url":"\/documentation\/iscp\/connection\/openupstream(sessionid:expiryinterval:dataids:qos:ackinterval:persist:flushpolicy:closetimeout:completion:)","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"アップストリームを開きます。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/openUpstream(sessionID:expiryInterval:dataIDs:qos:ackInterval:persist:flushPolicy:closeTimeout:completion:)","title":"openUpstream(sessionID:expiryInterval:dataIDs:qos:ackInterval:persist:flushPolicy:closeTimeout:completion:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DataID":{"title":"DataID","abstract":[{"text":"データポイントの、名称とデータ型を表す識別子です。","type":"text"}],"url":"\/documentation\/iscp\/dataid","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DataID"}],"navigatorTitle":[{"text":"DataID","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataID"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","kind":"symbol","url":"\/documentation\/iscp","role":"collection","type":"topic","title":"iSCP"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/FlushPolicy":{"title":"FlushPolicy","abstract":[{"type":"text","text":"Upstreamのフラッシュの方法について定義します。"}],"url":"\/documentation\/iscp\/flushpolicy","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FlushPolicy"}],"navigatorTitle":[{"text":"FlushPolicy","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/FlushPolicy"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/QoS":{"title":"QoS","abstract":[{"type":"text","text":"QoSを表します。"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"QoS","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/QoS","navigatorTitle":[{"kind":"identifier","text":"QoS"}],"type":"topic","role":"symbol","url":"\/documentation\/iscp\/qos"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection":{"url":"\/documentation\/iscp\/connection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","kind":"symbol","title":"Connection","type":"topic","abstract":[{"type":"text","text":"iSCPのコネクションを表すクラスです。"}],"navigatorTitle":[{"kind":"identifier","text":"Connection"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Connection","kind":"identifier"}],"role":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream":{"abstract":[{"text":"アップストリームを表すクラスです。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","kind":"symbol","url":"\/documentation\/iscp\/upstream","role":"symbol","type":"topic","title":"Upstream","navigatorTitle":[{"kind":"identifier","text":"Upstream"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Upstream"}]}},"variantOverrides":[{"patch":[{"value":"Connection","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/title"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/fragments","op":"replace","value":[{"text":"Connection","kind":"identifier"}]},{"value":"Upstream","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/title"},{"value":[{"text":"Upstream","kind":"identifier"}],"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}