{"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection"]]},"abstract":[{"type":"text","text":"ダウンストリームを開きます。"}],"variants":[{"paths":["\/documentation\/iscp\/connection\/opendownstream(downstreamfilters:dataids:qos:omitemptychunk:expiryinterval:ackinterval:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","title":"openDownstream(downstreamFilters:dataIDs:qos:omitEmptyChunk:expiryInterval:ackInterval:completion:)","extendedModule":"iSCP","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openDownstream","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"downstreamFilters"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:4iSCP16DownstreamFilterV","text":"DownstreamFilter","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"dataIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP6DataIDV","text":"DataID"},{"text":"], ","kind":"text"},{"text":"qos","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"QoS","preciseIdentifier":"s:4iSCP3QoSO"},{"text":", ","kind":"text"},{"text":"omitEmptyChunk","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"expiryInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"ackInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"downstream"},{"kind":"text","text":": "},{"text":"Downstream","kind":"typeIdentifier","preciseIdentifier":"c:@M@iSCP@objc(cs)Downstream"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ()))","kind":"text"}],"externalID":"s:4iSCP10ConnectionC14openDownstream17downstreamFilters7dataIDs3qos14omitEmptyChunk14expiryInterval03ackN010completionySayAA0D6FilterVG_SayAA6DataIDVGAA3QoSOSbS2dyAA0D0CSg_s5Error_pSgtctF","modules":[{"name":"iSCP"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openDownstream","kind":"identifier"},{"kind":"text","text":"("},{"text":"downstreamFilters","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamFilter","preciseIdentifier":"s:4iSCP16DownstreamFilterV","text":"DownstreamFilter","kind":"typeIdentifier"},{"text":"] = [], ","kind":"text"},{"text":"dataIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataID","preciseIdentifier":"s:4iSCP6DataIDV","text":"DataID","kind":"typeIdentifier"},{"text":"] = [], ","kind":"text"},{"text":"qos","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:4iSCP3QoSO","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/QoS","kind":"typeIdentifier","text":"QoS"},{"kind":"text","text":" = Downstream.DEFAULT_QOS, "},{"text":"omitEmptyChunk","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = Downstream.DEFAULT_OMIT_EMPTY_CHUNK, "},{"text":"expiryInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" = Downstream.DEFAULT_EXPIRY_INTERVAL, ","kind":"text"},{"text":"ackInterval","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":" = Downstream.DEFAULT_ACK_INTERVAL, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"downstream"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@iSCP@objc(cs)Downstream","kind":"typeIdentifier","text":"Downstream","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> ()))"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"ダウンストリームフィルター。"}],"type":"paragraph"}],"name":"downstreamFilters"},{"content":[{"inlineContent":[{"type":"text","text":"エイリアスを設定するデータIDのリスト。"}],"type":"paragraph"}],"name":"dataIDs"},{"name":"qos","content":[{"inlineContent":[{"text":"QoS。現在は ","type":"text"},{"type":"codeVoice","code":"unreliable"},{"type":"text","text":" のみサポート。"}],"type":"paragraph"}]},{"name":"omitEmptyChunk","content":[{"inlineContent":[{"text":"空チャンク省略フラグ。trueの場合、DownstreamChunk内のdataPointGroupsが空の時、DownstreamChunkの送信を省略します。","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"有効期限。このストリームが異常切断された時点からの有効期限を表します。最小値の ","type":"text"},{"code":"0","type":"codeVoice"},{"text":" は、異常切断されたと同時に有効期限切れとなることを表します。","type":"text"}],"type":"paragraph"}],"name":"expiryInterval"},{"name":"ackInterval","content":[{"type":"paragraph","inlineContent":[{"text":"Ack返却間隔。受信したメッセージに対するAckの返却間隔です。","type":"text"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"処理完了時のコールバック。"}]}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/openDownstream(downstreamFilters:dataIDs:qos:omitEmptyChunk:expiryInterval:ackInterval:completion:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/openDownstream(downstreamFilters:dataIDs:qos:omitEmptyChunk:expiryInterval:ackInterval:completion:)":{"abstract":[{"text":"ダウンストリームを開きます。","type":"text"}],"title":"openDownstream(downstreamFilters:dataIDs:qos:omitEmptyChunk:expiryInterval:ackInterval:completion:)","kind":"symbol","url":"\/documentation\/iscp\/connection\/opendownstream(downstreamfilters:dataids:qos:omitemptychunk:expiryinterval:ackinterval:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"openDownstream","kind":"identifier"},{"kind":"text","text":"("},{"text":"downstreamFilters","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DownstreamFilter","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP16DownstreamFilterV"},{"text":"], ","kind":"text"},{"text":"dataIDs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DataID","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP6DataIDV"},{"kind":"text","text":"], "},{"text":"qos","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"QoS","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP3QoSO"},{"text":", ","kind":"text"},{"text":"omitEmptyChunk","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"expiryInterval"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"ackInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"downstream"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@iSCP@objc(cs)Downstream","text":"Downstream"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> ()))"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/openDownstream(downstreamFilters:dataIDs:qos:omitEmptyChunk:expiryInterval:ackInterval:completion:)","role":"symbol","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream":{"abstract":[{"type":"text","text":"ダウンストリームを表すクラスです。"}],"navigatorTitle":[{"kind":"identifier","text":"Downstream"}],"type":"topic","kind":"symbol","url":"\/documentation\/iscp\/downstream","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Downstream","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","title":"Downstream"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"kind":"symbol","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"url":"\/documentation\/iscp","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DataID":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DataID","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataID","title":"DataID","url":"\/documentation\/iscp\/dataid","navigatorTitle":[{"text":"DataID","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"データポイントの、名称とデータ型を表す識別子です。","type":"text"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/QoS":{"navigatorTitle":[{"text":"QoS","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/iscp\/qos","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"QoS","kind":"identifier"}],"abstract":[{"type":"text","text":"QoSを表します。"}],"title":"QoS","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/QoS"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Connection","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","url":"\/documentation\/iscp\/connection","title":"Connection","abstract":[{"text":"iSCPのコネクションを表すクラスです。","type":"text"}],"navigatorTitle":[{"text":"Connection","kind":"identifier"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DownstreamFilter":{"title":"DownstreamFilter","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DownstreamFilter"}],"abstract":[{"type":"text","text":"ダウンストリームフィルタです。"}],"kind":"symbol","type":"topic","url":"\/documentation\/iscp\/downstreamfilter","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DownstreamFilter","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DownstreamFilter"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Downstream","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/title"},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/fragments","value":[{"text":"Downstream","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/navigatorTitle","value":[{"text":"Downstream","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/title","value":"Connection"},{"op":"replace","value":[{"text":"Connection","kind":"identifier"}],"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/fragments"},{"value":[{"text":"Connection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/navigatorTitle"}]}]}