{"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection"]]},"abstract":[{"type":"text","text":"アップストリームを開きます。"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscp\/connection\/openupstream(sessionid:expiryinterval:dataids:qos:ackinterval:persist:flushpolicy:opentimeout:closetimeout:completion:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openUpstream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expiryInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":" = Upstream.DEFAULT_EXPIRY_INTERVAL, "},{"kind":"externalParam","text":"dataIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP6DataIDV","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataID","text":"DataID"},{"kind":"text","text":"] = [], "},{"kind":"externalParam","text":"qos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP3QoSO","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/QoS","text":"QoS"},{"kind":"text","text":" = Upstream.DEFAULT_QOS, "},{"kind":"externalParam","text":"ackInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":" = Upstream.DEFAULT_ACK_INTERVAL, "},{"kind":"externalParam","text":"persist"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = Upstream.DEFAULT_PERSIST, "},{"kind":"externalParam","text":"flushPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP11FlushPolicyV","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/FlushPolicy","text":"FlushPolicy"},{"kind":"text","text":" = Upstream.DEFAULT_FLUSH_POLICY, "},{"kind":"externalParam","text":"openTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":" = Upstream.DEFAULT_OPEN_TIMEOUT, "},{"kind":"externalParam","text":"closeTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":" = Upstream.DEFAULT_CLOSE_TIMEOUT, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"upstream"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","text":"Upstream"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> ()))"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"セッションID。"}],"type":"paragraph"}],"name":"sessionID"},{"name":"expiryInterval","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"有効期限。このストリームが異常切断された時点からの有効期限を表します。最小値の "},{"type":"codeVoice","code":"0"},{"type":"text","text":" は、異常切断されたと同時に有効期限切れとなることを表します。"}]}]},{"name":"dataIDs","content":[{"type":"paragraph","inlineContent":[{"text":"送信予定のデータIDのリスト。送信されるデータのデータIDが ","type":"text"},{"code":"dataIDs","type":"codeVoice"},{"text":" に含まれていなかった場合、自動的にそのデータIDが ","type":"text"},{"code":"dataIDs","type":"codeVoice"},{"text":" に追加されます（そのため、","type":"text"},{"code":"dataIDs","type":"codeVoice"},{"text":" に空のリストが設定されていても問題ありません）。","type":"text"}]}]},{"name":"qos","content":[{"inlineContent":[{"type":"text","text":"QoS。現在は "},{"type":"codeVoice","code":"unreliable"},{"type":"text","text":" のみサポート。"}],"type":"paragraph"}]},{"name":"ackInterval","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Ack返却間隔。このストリームで送信されたデータに対する確認応答の間隔を表します。"},{"type":"codeVoice","code":"0"},{"type":"text","text":" が設定された場合、ブローカーは1つの "},{"type":"codeVoice","code":"UpstreamChunk"},{"type":"text","text":" メッセージごとに 1つの "},{"type":"codeVoice","code":"UpstreamChunkAck"},{"type":"text","text":" メッセージを返却します。"}]}]},{"name":"persist","content":[{"inlineContent":[{"type":"text","text":"永続化するかどうか。"}],"type":"paragraph"}]},{"name":"flushPolicy","content":[{"type":"paragraph","inlineContent":[{"text":"データポイントのフラッシュポリシー。","type":"text"}]}]},{"name":"openTimeout","content":[{"inlineContent":[{"type":"text","text":"オープンのタイムアウト。 "},{"code":"0","type":"codeVoice"},{"type":"text","text":" 以下の場合はタイムアウトしません。"}],"type":"paragraph"}]},{"name":"closeTimeout","content":[{"inlineContent":[{"text":"クローズのタイムアウト。 ","type":"text"},{"type":"codeVoice","code":"0"},{"text":" 以下の場合はタイムアウトしません。","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"処理完了時のコールバック。","type":"text"}]}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/openUpstream(sessionID:expiryInterval:dataIDs:qos:ackInterval:persist:flushPolicy:openTimeout:closeTimeout:completion:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"iSCP"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openUpstream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expiryInterval"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dataIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DataID","preciseIdentifier":"s:4iSCP6DataIDV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"qos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP3QoSO","text":"QoS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ackInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"persist"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"flushPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP11FlushPolicyV","text":"FlushPolicy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"openTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"closeTimeout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"upstream"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Upstream","preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ()))","kind":"text"}],"extendedModule":"iSCP","externalID":"s:4iSCP10ConnectionC12openUpstream9sessionID14expiryInterval7dataIDs3qos03ackH07persist11flushPolicy0C7Timeout05closeP010completionySS_SdSayAA04DataF0VGAA3QoSOSdSbAA05FlushO0VS2dyAA0D0CSg_s5Error_pSgtctF","symbolKind":"method","roleHeading":"Instance Method","title":"openUpstream(sessionID:expiryInterval:dataIDs:qos:ackInterval:persist:flushPolicy:openTimeout:closeTimeout:completion:)"},"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/openUpstream(sessionID:expiryInterval:dataIDs:qos:ackInterval:persist:flushPolicy:openTimeout:closeTimeout:completion:)":{"type":"topic","abstract":[{"type":"text","text":"アップストリームを開きます。"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openUpstream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expiryInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dataIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP6DataIDV","text":"DataID"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"qos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP3QoSO","text":"QoS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ackInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"persist"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"flushPolicy"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4iSCP11FlushPolicyV","kind":"typeIdentifier","text":"FlushPolicy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"openTimeout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"closeTimeout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"upstream"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream","kind":"typeIdentifier","text":"Upstream"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ()))"}],"kind":"symbol","url":"\/documentation\/iscp\/connection\/openupstream(sessionid:expiryinterval:dataids:qos:ackinterval:persist:flushpolicy:opentimeout:closetimeout:completion:)","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/openUpstream(sessionID:expiryInterval:dataIDs:qos:ackInterval:persist:flushPolicy:openTimeout:closeTimeout:completion:)","title":"openUpstream(sessionID:expiryInterval:dataIDs:qos:ackInterval:persist:flushPolicy:openTimeout:closeTimeout:completion:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream":{"navigatorTitle":[{"kind":"identifier","text":"Upstream"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Upstream"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/upstream","kind":"symbol","title":"Upstream","abstract":[{"text":"アップストリームを表すクラスです。","type":"text"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"type":"topic","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","url":"\/documentation\/iscp","kind":"symbol","role":"collection"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DataID":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DataID","kind":"identifier"}],"navigatorTitle":[{"text":"DataID","kind":"identifier"}],"kind":"symbol","title":"DataID","role":"symbol","url":"\/documentation\/iscp\/dataid","abstract":[{"type":"text","text":"データポイントの、名称とデータ型を表す識別子です。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataID","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection":{"navigatorTitle":[{"kind":"identifier","text":"Connection"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Connection"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/connection","title":"Connection","abstract":[{"type":"text","text":"iSCPのコネクションを表すクラスです。"}],"kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/QoS":{"title":"QoS","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"QoS","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"QoS"}],"type":"topic","role":"symbol","abstract":[{"type":"codeVoice","code":"QoS"},{"type":"text","text":" を表します。"}],"url":"\/documentation\/iscp\/qos","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/QoS"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/FlushPolicy":{"type":"topic","abstract":[{"code":"Upstream","type":"codeVoice"},{"type":"text","text":" のフラッシュの方法について定義します。"}],"navigatorTitle":[{"kind":"identifier","text":"FlushPolicy"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"FlushPolicy","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/iscp\/flushpolicy","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/FlushPolicy","title":"FlushPolicy"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/title","value":"Upstream"},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/fragments","value":[{"text":"Upstream","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/navigatorTitle","value":[{"kind":"identifier","text":"Upstream"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/title","value":"Connection"},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/fragments","value":[{"kind":"identifier","text":"Connection"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/navigatorTitle","value":[{"kind":"identifier","text":"Connection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}