{"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reopenUpstream"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream","kind":"typeIdentifier","text":"Upstream"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handoverDataPoints"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"upstream"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream","kind":"typeIdentifier","text":"Upstream"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ()))"}],"extendedModule":"iSCP","title":"reopenUpstream(_:handoverDataPoints:completion:)","role":"symbol","symbolKind":"method","modules":[{"name":"iSCP"}],"externalID":"s:4iSCP10ConnectionC14reopenUpstream_18handoverDataPoints10completionyAA0D0C_SbyAHSg_s5Error_pSgtctF","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reopenUpstream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"upstream"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream","kind":"typeIdentifier","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","text":"Upstream"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handoverDataPoints"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"upstream"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream","kind":"typeIdentifier","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","text":"Upstream"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ()))"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"既存のアップストリーム。このアップストリームの設定を引き継ぐ別のアップストリームが開かれます。","type":"text"}],"type":"paragraph"}],"name":"upstream"},{"content":[{"inlineContent":[{"text":"未送信のデータポイントが存在すれば引き継ぐかどうか。","type":"text"}],"type":"paragraph"}],"name":"handoverDataPoints"},{"content":[{"inlineContent":[{"text":"処理完了時のコールバック。","type":"text"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"ストリーム設定を引き継いで別ストリームとして再度アップストリームを開きます。"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscp\/connection\/reopenupstream(_:handoverdatapoints:completion:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/reopenUpstream(_:handoverDataPoints:completion:)"},"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"type":"topic","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","url":"\/documentation\/iscp","kind":"symbol","role":"collection"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/reopenUpstream(_:handoverDataPoints:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reopenUpstream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Upstream","preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handoverDataPoints"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"upstream"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Upstream","preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ()))"}],"title":"reopenUpstream(_:handoverDataPoints:completion:)","kind":"symbol","role":"symbol","url":"\/documentation\/iscp\/connection\/reopenupstream(_:handoverdatapoints:completion:)","abstract":[{"type":"text","text":"ストリーム設定を引き継いで別ストリームとして再度アップストリームを開きます。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/reopenUpstream(_:handoverDataPoints:completion:)","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream":{"navigatorTitle":[{"kind":"identifier","text":"Upstream"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Upstream"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/upstream","kind":"symbol","title":"Upstream","abstract":[{"text":"アップストリームを表すクラスです。","type":"text"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection":{"navigatorTitle":[{"kind":"identifier","text":"Connection"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Connection"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/connection","title":"Connection","abstract":[{"type":"text","text":"iSCPのコネクションを表すクラスです。"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"Upstream","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/title"},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/fragments","value":[{"text":"Upstream","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/navigatorTitle","value":[{"text":"Upstream","kind":"identifier"}]},{"value":"Connection","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Connection"}],"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/fragments"},{"op":"replace","value":[{"text":"Connection","kind":"identifier"}],"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}