{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenSource"},{"kind":"text","text":": (("},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"token"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> ()) -> ())"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"tokenSource","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tokenSource","kind":"identifier"},{"text":": (((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"token","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ()) -> ())","kind":"text"}],"modules":[{"name":"iSCP"}],"role":"symbol","externalID":"s:4iSCP10ConnectionC11tokenSourceyyySSSgccvp","roleHeading":"Instance Property","symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection"]]},"identifier":{"url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/tokenSource","interfaceLanguage":"swift"},"abstract":[{"text":"トークンソース。","type":"text"}],"variants":[{"paths":["\/documentation\/iscp\/connection\/tokensource"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection":{"navigatorTitle":[{"kind":"identifier","text":"Connection"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Connection"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/connection","title":"Connection","abstract":[{"type":"text","text":"iSCPのコネクションを表すクラスです。"}],"kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/tokenSource":{"title":"tokenSource","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tokenSource","kind":"identifier"},{"text":": (((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"token","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) -> ()) -> ())"}],"type":"topic","role":"symbol","abstract":[{"text":"トークンソース。","type":"text"}],"url":"\/documentation\/iscp\/connection\/tokensource","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/tokenSource"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"type":"topic","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","url":"\/documentation\/iscp","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"Connection","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/title"},{"value":[{"text":"Connection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/fragments"},{"value":[{"kind":"identifier","text":"Connection"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}