{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transportConfig","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ITransportConfig","text":"ITransportConfig","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP16ITransportConfigP"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscp\/connection\/transportconfig"]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection"]]},"abstract":[{"text":"トランスポートの設定。","type":"text"}],"metadata":{"modules":[{"name":"iSCP"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transportConfig"},{"text":": ","kind":"text"},{"text":"ITransportConfig","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP16ITransportConfigP"}],"symbolKind":"property","title":"transportConfig","role":"symbol","roleHeading":"Instance Property","externalID":"s:4iSCP10ConnectionC15transportConfigAA010ITransportD0_pvp"},"identifier":{"url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/transportConfig","interfaceLanguage":"swift"},"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/ITransportConfig":{"url":"\/documentation\/iscp\/itransportconfig","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ITransportConfig","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ITransportConfig"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ITransportConfig"}],"abstract":[{"text":"トランスポートの設定のインターフェイスです。","type":"text"}],"kind":"symbol","title":"ITransportConfig"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Connection","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","url":"\/documentation\/iscp\/connection","title":"Connection","abstract":[{"text":"iSCPのコネクションを表すクラスです。","type":"text"}],"navigatorTitle":[{"text":"Connection","kind":"identifier"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/transportConfig":{"abstract":[{"type":"text","text":"トランスポートの設定。"}],"kind":"symbol","title":"transportConfig","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"transportConfig"},{"kind":"text","text":": "},{"text":"ITransportConfig","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP16ITransportConfigP"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/transportConfig","url":"\/documentation\/iscp\/connection\/transportconfig","role":"symbol","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"kind":"symbol","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"url":"\/documentation\/iscp","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/title","value":"Connection","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/fragments","value":[{"text":"Connection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/navigatorTitle","value":[{"kind":"identifier","text":"Connection"}],"op":"replace"}]}]}