{"metadata":{"extendedModule":"Swift","modules":[{"name":"iSCP","relatedModules":["Swift"]}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Operator","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::s:4iSCP10DownstreamC5StateV","title":"!=(_:_:)","symbolKind":"op"},"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State\/Equatable-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"text":".","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State\/!=(_:_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscp\/downstream\/state\/!=(_:_:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"kind":"symbol","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"url":"\/documentation\/iscp","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream":{"abstract":[{"type":"text","text":"ダウンストリームを表すクラスです。"}],"navigatorTitle":[{"kind":"identifier","text":"Downstream"}],"type":"topic","kind":"symbol","url":"\/documentation\/iscp\/downstream","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Downstream","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","title":"Downstream"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/State/!=(_:_:)":{"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State\/!=(_:_:)","title":"!=(_:_:)","role":"symbol","url":"\/documentation\/iscp\/downstream\/state\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/State":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State","title":"Downstream.State","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"State","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"State"}],"kind":"symbol","url":"\/documentation\/iscp\/downstream\/state","abstract":[{"type":"text","text":"ダウンストリームの状態を表します。"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/State/Equatable-Implementations":{"kind":"article","role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State\/Equatable-Implementations","type":"topic","abstract":[],"url":"\/documentation\/iscp\/downstream\/state\/equatable-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Downstream","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/title"},{"value":[{"kind":"identifier","text":"Downstream"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/fragments"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/navigatorTitle","op":"replace","value":[{"text":"Downstream","kind":"identifier"}]}]}]}