{"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State"]]},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"=="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"preciseIdentifier":"s:4iSCP10DownstreamC5StateV","text":"State","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"s:4iSCP10DownstreamC5StateV","text":"State","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","title":"==(_:_:)","modules":[{"name":"iSCP"}],"externalID":"s:4iSCP10DownstreamC5StateV2eeoiySbAE_AEtFZ","roleHeading":"Operator","symbolKind":"op"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/iscp\/downstream\/state\/==(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"=="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"s:4iSCP10DownstreamC5StateV","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4iSCP10DownstreamC5StateV","kind":"typeIdentifier","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State","text":"State"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State\/==(_:_:)"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"Equatable.==(_:_:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream":{"title":"Downstream","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Downstream"}],"navigatorTitle":[{"kind":"identifier","text":"Downstream"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"ダウンストリームを表すクラスです。"}],"url":"\/documentation\/iscp\/downstream","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"type":"topic","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","url":"\/documentation\/iscp","kind":"symbol","role":"collection"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/State":{"title":"Downstream.State","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"State"}],"navigatorTitle":[{"text":"State","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"ダウンストリームの状態を表します。"}],"url":"\/documentation\/iscp\/downstream\/state","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/State/==(_:_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"=="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"preciseIdentifier":"s:4iSCP10DownstreamC5StateV","kind":"typeIdentifier","text":"State"},{"kind":"text","text":", "},{"preciseIdentifier":"s:4iSCP10DownstreamC5StateV","kind":"typeIdentifier","text":"State"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/iscp\/downstream\/state\/==(_:_:)","title":"==(_:_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State\/==(_:_:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/title","value":"Downstream"},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/fragments","value":[{"kind":"identifier","text":"Downstream"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/navigatorTitle","value":[{"kind":"identifier","text":"Downstream"}]}]}]}