{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"データIDエイリアスとデータIDのマップ。"}],"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State\/dataIDAliases"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataIDAliases"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SD","text":"Dictionary"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":", "},{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataID","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP6DataIDV","text":"DataID"},{"kind":"text","text":">"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscp\/downstream\/state\/dataidaliases"]}],"metadata":{"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"s:4iSCP10DownstreamC5StateV13dataIDAliasesSDys6UInt32VAA6DataIDVGvp","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataIDAliases"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DataID","preciseIdentifier":"s:4iSCP6DataIDV"},{"kind":"text","text":">"}],"modules":[{"name":"iSCP"}],"title":"dataIDAliases"},"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"title":"iSCP","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","url":"\/documentation\/iscp","type":"topic","kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/State/dataIDAliases":{"abstract":[{"text":"データIDエイリアスとデータIDのマップ。","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State\/dataIDAliases","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataIDAliases"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SD","kind":"typeIdentifier","text":"Dictionary"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"},{"kind":"text","text":", "},{"preciseIdentifier":"s:4iSCP6DataIDV","kind":"typeIdentifier","text":"DataID"},{"kind":"text","text":">"}],"type":"topic","url":"\/documentation\/iscp\/downstream\/state\/dataidaliases","title":"dataIDAliases"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/State":{"url":"\/documentation\/iscp\/downstream\/state","title":"Downstream.State","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"ダウンストリームの状態を表します。"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"navigatorTitle":[{"kind":"identifier","text":"State"}],"type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DataID":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataID","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"DataID","kind":"identifier"}],"abstract":[{"text":"データポイントの、名称とデータ型を表す識別子です。","type":"text"}],"url":"\/documentation\/iscp\/dataid","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataID","kind":"identifier"}],"title":"DataID"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","role":"symbol","url":"\/documentation\/iscp\/downstream","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Downstream","kind":"identifier"}],"title":"Downstream","kind":"symbol","abstract":[{"type":"text","text":"ダウンストリームを表すクラスです。"}],"navigatorTitle":[{"text":"Downstream","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/title","value":"Downstream","op":"replace"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/fragments","value":[{"text":"Downstream","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/navigatorTitle","value":[{"text":"Downstream","kind":"identifier"}],"op":"replace"}]}]}