{"metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"connection","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@iSCP@objc(cs)Connection","kind":"typeIdentifier","text":"Connection"}],"symbolKind":"property","externalID":"s:4iSCP10DownstreamC10connectionAA10ConnectionCvp","modules":[{"name":"iSCP"}],"roleHeading":"Instance Property","title":"connection"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream"]]},"variants":[{"paths":["\/documentation\/iscp\/downstream\/connection"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/connection","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Connection","preciseIdentifier":"c:@M@iSCP@objc(cs)Connection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"コネクション。"}],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream":{"abstract":[{"type":"text","text":"ダウンストリームを表すクラスです。"}],"navigatorTitle":[{"kind":"identifier","text":"Downstream"}],"type":"topic","kind":"symbol","url":"\/documentation\/iscp\/downstream","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Downstream","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","title":"Downstream"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/connection":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/connection","title":"connection","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"connection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@iSCP@objc(cs)Connection","text":"Connection","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/iscp\/downstream\/connection","abstract":[{"type":"text","text":"コネクション。"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"kind":"symbol","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"url":"\/documentation\/iscp","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Connection","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","url":"\/documentation\/iscp\/connection","title":"Connection","abstract":[{"text":"iSCPのコネクションを表すクラスです。","type":"text"}],"navigatorTitle":[{"text":"Connection","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/title","value":"Downstream"},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/fragments","value":[{"text":"Downstream","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/navigatorTitle","value":[{"kind":"identifier","text":"Downstream"}]},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/title","value":"Connection","op":"replace"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/fragments","op":"replace","value":[{"kind":"identifier","text":"Connection"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/navigatorTitle","value":[{"kind":"identifier","text":"Connection"}]}]}]}