{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/DEFAULT_QOS"},"variants":[{"paths":["\/documentation\/iscp\/downstream\/default_qos"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"title":"DEFAULT_QOS","modules":[{"name":"iSCP"}],"externalID":"s:4iSCP10DownstreamC11DEFAULT_QOSAA3QoSOvpZ","roleHeading":"Type Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_QOS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QoS","preciseIdentifier":"s:4iSCP3QoSO"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_QOS"},{"kind":"text","text":": "},{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/QoS","preciseIdentifier":"s:4iSCP3QoSO","kind":"typeIdentifier","text":"QoS"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream"]]},"abstract":[{"type":"text","text":"QoSのデフォルト値。"}],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/DEFAULT_QOS":{"role":"symbol","abstract":[{"text":"QoSのデフォルト値。","type":"text"}],"title":"DEFAULT_QOS","url":"\/documentation\/iscp\/downstream\/default_qos","kind":"symbol","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/DEFAULT_QOS","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DEFAULT_QOS","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QoS","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP3QoSO"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"title":"iSCP","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","url":"\/documentation\/iscp","type":"topic","kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","role":"symbol","url":"\/documentation\/iscp\/downstream","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Downstream","kind":"identifier"}],"title":"Downstream","kind":"symbol","abstract":[{"type":"text","text":"ダウンストリームを表すクラスです。"}],"navigatorTitle":[{"text":"Downstream","kind":"identifier"}],"type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/QoS":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/QoS","title":"QoS","abstract":[{"type":"text","text":"QoSを表します。"}],"navigatorTitle":[{"kind":"identifier","text":"QoS"}],"url":"\/documentation\/iscp\/qos","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"QoS"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/title","value":"Downstream"},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/fragments","value":[{"kind":"identifier","text":"Downstream"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/navigatorTitle","value":[{"kind":"identifier","text":"Downstream"}]}]}]}