{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream"]]},"variants":[{"paths":["\/documentation\/iscp\/downstream\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/iscp\/downstream\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","modules":[{"name":"iSCP"}],"externalID":"c:@M@iSCP@objc(cs)Downstream(im)isEqual:","roleHeading":"Instance Method","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/isEqual(_:)"},"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"title":"iSCP","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","url":"\/documentation\/iscp","type":"topic","kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","role":"symbol","url":"\/documentation\/iscp\/downstream","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Downstream","kind":"identifier"}],"title":"Downstream","kind":"symbol","abstract":[{"type":"text","text":"ダウンストリームを表すクラスです。"}],"navigatorTitle":[{"text":"Downstream","kind":"identifier"}],"type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[],"title":"isEqual(_:)","url":"\/documentation\/iscp\/downstream\/isequal(_:)","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"isEqual:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"Downstream","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/title"},{"op":"replace","value":[{"text":"Downstream","kind":"identifier"}],"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/fragments"},{"op":"replace","value":[{"text":"Downstream","kind":"identifier"}],"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/navigatorTitle"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream~1isEqual(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream~1isEqual(_:)\/fragments"}]}]}