{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"openTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/iscp\/downstream\/opentimeout"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","symbolKind":"property","externalID":"s:4iSCP10DownstreamC11openTimeoutSdvp","roleHeading":"Instance Property","title":"openTimeout","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"modules":[{"name":"iSCP"}]},"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream"]]},"abstract":[{"text":"オープンのタイムアウト。","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/openTimeout"},"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/openTimeout":{"url":"\/documentation\/iscp\/downstream\/opentimeout","kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/openTimeout","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"openTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"text":"オープンのタイムアウト。","type":"text"}],"title":"openTimeout"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"title":"iSCP","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","url":"\/documentation\/iscp","type":"topic","kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","role":"symbol","url":"\/documentation\/iscp\/downstream","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Downstream","kind":"identifier"}],"title":"Downstream","kind":"symbol","abstract":[{"type":"text","text":"ダウンストリームを表すクラスです。"}],"navigatorTitle":[{"text":"Downstream","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/title","value":"Downstream","op":"replace"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/fragments","value":[{"kind":"identifier","text":"Downstream"}],"op":"replace"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/navigatorTitle","value":[{"kind":"identifier","text":"Downstream"}],"op":"replace"}]}]}