{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscp\/upstream\/state\/!=(_:_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/State\/!=(_:_:)"},"metadata":{"modules":[{"name":"iSCP","relatedModules":["Swift"]}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::s:4iSCP8UpstreamC5StateV","role":"symbol","extendedModule":"Swift","symbolKind":"op","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Operator","title":"!=(_:_:)"},"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/State","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/State\/Equatable-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]}],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream":{"title":"Upstream","url":"\/documentation\/iscp\/upstream","abstract":[{"type":"text","text":"アップストリームを表すクラスです。"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Upstream","kind":"identifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","navigatorTitle":[{"text":"Upstream","kind":"identifier"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/State":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"navigatorTitle":[{"kind":"identifier","text":"State"}],"title":"Upstream.State","abstract":[{"type":"text","text":"アップストリームの状態を表します。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/State","type":"topic","url":"\/documentation\/iscp\/upstream\/state","kind":"symbol","role":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/State/Equatable-Implementations":{"role":"collectionGroup","url":"\/documentation\/iscp\/upstream\/state\/equatable-implementations","title":"Equatable Implementations","type":"topic","abstract":[],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/State\/Equatable-Implementations","kind":"article"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/State/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/State\/!=(_:_:)","abstract":[],"type":"topic","url":"\/documentation\/iscp\/upstream\/state\/!=(_:_:)","role":"symbol","title":"!=(_:_:)","kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"title":"iSCP","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","url":"\/documentation\/iscp","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/title","op":"replace","value":"Upstream"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/fragments","op":"replace","value":[{"text":"Upstream","kind":"identifier"}]},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Upstream"}]}]}]}