{"variants":[{"paths":["\/documentation\/iscp\/upstream\/state\/datapointgroups"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"送信予定のデータポイントグループのリスト。"}],"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/State"]]},"metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataPointGroups"},{"kind":"text","text":": ["},{"text":"DataPointGroup","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP14DataPointGroupV"},{"kind":"text","text":"]"}],"modules":[{"name":"iSCP"}],"symbolKind":"property","title":"dataPointGroups","externalID":"s:4iSCP8UpstreamC5StateV15dataPointGroupsSayAA04DataE5GroupVGvp"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataPointGroups"},{"text":": [","kind":"text"},{"text":"DataPointGroup","kind":"typeIdentifier","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataPointGroup","preciseIdentifier":"s:4iSCP14DataPointGroupV"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/State\/dataPointGroups"},"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/State":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"navigatorTitle":[{"text":"State","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"アップストリームの状態を表します。"}],"url":"\/documentation\/iscp\/upstream\/state","type":"topic","title":"Upstream.State","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/State"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/State/dataPointGroups":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/State\/dataPointGroups","url":"\/documentation\/iscp\/upstream\/state\/datapointgroups","type":"topic","title":"dataPointGroups","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataPointGroups"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:4iSCP14DataPointGroupV","kind":"typeIdentifier","text":"DataPointGroup"},{"text":"]","kind":"text"}],"abstract":[{"text":"送信予定のデータポイントグループのリスト。","type":"text"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"kind":"symbol","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"url":"\/documentation\/iscp","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/DataPointGroup":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DataPointGroup"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DataPointGroup","kind":"identifier"}],"url":"\/documentation\/iscp\/datapointgroup","title":"DataPointGroup","type":"topic","kind":"symbol","abstract":[{"text":"ストリームチャンクの中のデータポイントをデータIDごとにまとめた集合です。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/DataPointGroup"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream":{"abstract":[{"type":"text","text":"アップストリームを表すクラスです。"}],"navigatorTitle":[{"text":"Upstream","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","url":"\/documentation\/iscp\/upstream","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Upstream"}],"kind":"symbol","title":"Upstream"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Upstream","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/fragments","value":[{"kind":"identifier","text":"Upstream"}]},{"value":[{"text":"Upstream","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/navigatorTitle"}]}]}