{"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ITransportDelegate","doc:\/\/jp.co.aptpod.iSCP\/objc(pl)NSObject","doc:\/\/jp.co.aptpod.iSCP\/s7CVarArgP","doc:\/\/jp.co.aptpod.iSCP\/s8CopyableP","doc:\/\/jp.co.aptpod.iSCP\/s28CustomDebugStringConvertibleP","doc:\/\/jp.co.aptpod.iSCP\/s23CustomStringConvertibleP","doc:\/\/jp.co.aptpod.iSCP\/SQ","doc:\/\/jp.co.aptpod.iSCP\/s9EscapableP","doc:\/\/jp.co.aptpod.iSCP\/SH"]}],"kind":"symbol","topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/init(address:connector:tokenSource:nodeID:projectUUID:connectTimeout:pingTimeout:pingInterval:autoReconnect:reconnectBaseInterval:reconnectMaxInterval:encoding:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/address","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/autoReconnect","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/connectTimeout","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/connector","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/delegate","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/e2eCallDelegate","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/encoding","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/isConnecting","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/isOpen","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/isReconnecting","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/nodeID","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/pingInterval","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/pingTimeout","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/projectUUID","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/protocolVersion","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/reconnectBaseInterval","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/reconnectMaxInterval","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/tag","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/tokenSource"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/close(completion:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/connect(completion:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/openDownstream(downstreamFilters:dataIDs:qos:omitEmptyChunk:expiryInterval:ackInterval:openTimeout:closeTimeout:completion:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/openUpstream(sessionID:expiryInterval:dataIDs:qos:ackInterval:persist:flushPolicy:openTimeout:closeTimeout:completion:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/reopenDownstream(_:completion:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/reopenUpstream(_:handoverDataPoints:completion:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/sendBaseTime(baseTime:persist:sendTimeout:completion:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/sendCall(upstreamCall:sendTimeout:completion:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/sendCallAndWaitReplayCall(upstreamCall:sendTimeout:waitTimeout:completion:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/sendCallAndWaitReplyCall(upstreamCall:sendTimeout:waitTimeout:completion:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/sendReplyCall(upstreamReplyCall:sendTimeout:completion:)"]},{"title":"Type Properties","anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_AUTO_RECONNECT","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_CONNECT_TIMEOUT","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_E2E_CALL_TIMEOUT","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_ENCODING","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_PING_INTERVAL","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_PING_TIMEOUT","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_RECONNECT_BASE_INTERVAL","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_RECONNECT_MAX_INTERVAL","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_SEND_METADATA_TIMEOUT"]},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/connect(address:connector:tokenSource:nodeID:projectUUID:connectTimeout:pingTimeout:pingInterval:autoReconnect:reconnectBaseInterval:reconnectMaxInterval:encoding:delegate:e2eCallDelegate:completion:)"]},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/ITransportDelegate-Implementations"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscp\/connection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iscp\/connection"]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Connection"}],"role":"symbol","title":"Connection","modules":[{"name":"iSCP"}],"externalID":"c:@M@iSCP@objc(cs)Connection","navigatorTitle":[{"kind":"identifier","text":"Connection"}],"roleHeading":"Class","symbolKind":"class"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"iSCPのコネクションを表すクラスです。"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Connection"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP"]]},"identifier":{"url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","interfaceLanguage":"swift"},"sections":[],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/close(completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"close"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ())?)"}],"role":"symbol","url":"\/documentation\/iscp\/connection\/close(completion:)","title":"close(completion:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"コネクションを閉じます。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/close(completion:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/encoding":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"encoding","kind":"identifier"},{"text":": ","kind":"text"},{"text":"EncodingName","preciseIdentifier":"s:4iSCP12EncodingNameO","kind":"typeIdentifier"}],"url":"\/documentation\/iscp\/connection\/encoding","title":"encoding","kind":"symbol","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/encoding","abstract":[{"text":"エンコーディング名。","type":"text"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/autoReconnect":{"kind":"symbol","title":"autoReconnect","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoReconnect","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"自動で再接続するかどうか。"}],"url":"\/documentation\/iscp\/connection\/autoreconnect","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/autoReconnect"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/init(address:connector:tokenSource:nodeID:projectUUID:connectTimeout:pingTimeout:pingInterval:autoReconnect:reconnectBaseInterval:reconnectMaxInterval:encoding:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"address"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connector"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4iSCP10IConnectorP","kind":"typeIdentifier","text":"IConnector"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tokenSource"},{"kind":"text","text":": ((("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"token"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> ()) -> ()), "},{"kind":"externalParam","text":"nodeID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"projectUUID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectTimeout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pingTimeout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pingInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoReconnect"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reconnectBaseInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reconnectMaxInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encoding"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4iSCP12EncodingNameO","kind":"typeIdentifier","text":"EncodingName"},{"kind":"text","text":")"}],"url":"\/documentation\/iscp\/connection\/init(address:connector:tokensource:nodeid:projectuuid:connecttimeout:pingtimeout:pinginterval:autoreconnect:reconnectbaseinterval:reconnectmaxinterval:encoding:)","title":"init(address:connector:tokenSource:nodeID:projectUUID:connectTimeout:pingTimeout:pingInterval:autoReconnect:reconnectBaseInterval:reconnectMaxInterval:encoding:)","kind":"symbol","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/init(address:connector:tokenSource:nodeID:projectUUID:connectTimeout:pingTimeout:pingInterval:autoReconnect:reconnectBaseInterval:reconnectMaxInterval:encoding:)","abstract":[]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/DEFAULT_CONNECT_TIMEOUT":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_CONNECT_TIMEOUT"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"role":"symbol","url":"\/documentation\/iscp\/connection\/default_connect_timeout","title":"DEFAULT_CONNECT_TIMEOUT","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"コネクトのタイムアウトのデフォルト値。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_CONNECT_TIMEOUT"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/ITransportDelegate-Implementations":{"role":"collectionGroup","url":"\/documentation\/iscp\/connection\/itransportdelegate-implementations","kind":"article","type":"topic","title":"ITransportDelegate Implementations","abstract":[],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/ITransportDelegate-Implementations"},"doc://jp.co.aptpod.iSCP/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/SH"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/reopenUpstream(_:handoverDataPoints:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reopenUpstream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Upstream","preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handoverDataPoints"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"upstream"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Upstream","preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ()))"}],"title":"reopenUpstream(_:handoverDataPoints:completion:)","kind":"symbol","role":"symbol","url":"\/documentation\/iscp\/connection\/reopenupstream(_:handoverdatapoints:completion:)","abstract":[{"type":"text","text":"ストリーム設定を引き継いで別ストリームとして再度アップストリームを開きます。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/reopenUpstream(_:handoverDataPoints:completion:)","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/openDownstream(downstreamFilters:dataIDs:qos:omitEmptyChunk:expiryInterval:ackInterval:openTimeout:closeTimeout:completion:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openDownstream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"downstreamFilters","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DownstreamFilter","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP16DownstreamFilterV"},{"text":"], ","kind":"text"},{"text":"dataIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DataID","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP6DataIDV"},{"text":"], ","kind":"text"},{"text":"qos","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"QoS","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP3QoSO"},{"text":", ","kind":"text"},{"text":"omitEmptyChunk","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"expiryInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"ackInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"openTimeout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"closeTimeout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"downstream","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Downstream","kind":"typeIdentifier","preciseIdentifier":"c:@M@iSCP@objc(cs)Downstream"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ()))","kind":"text"}],"url":"\/documentation\/iscp\/connection\/opendownstream(downstreamfilters:dataids:qos:omitemptychunk:expiryinterval:ackinterval:opentimeout:closetimeout:completion:)","title":"openDownstream(downstreamFilters:dataIDs:qos:omitEmptyChunk:expiryInterval:ackInterval:openTimeout:closeTimeout:completion:)","kind":"symbol","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/openDownstream(downstreamFilters:dataIDs:qos:omitEmptyChunk:expiryInterval:ackInterval:openTimeout:closeTimeout:completion:)","abstract":[{"text":"ダウンストリームを開きます。","type":"text"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/DEFAULT_RECONNECT_BASE_INTERVAL":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_RECONNECT_BASE_INTERVAL"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"role":"symbol","url":"\/documentation\/iscp\/connection\/default_reconnect_base_interval","kind":"symbol","type":"topic","title":"DEFAULT_RECONNECT_BASE_INTERVAL","abstract":[{"type":"text","text":"自動で再接続する際の、リトライ間隔の初期値のデフォルト値。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_RECONNECT_BASE_INTERVAL"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/tag":{"title":"tag","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","role":"symbol","abstract":[{"text":"オブジェクトを識別するためのタグ。","type":"text"}],"url":"\/documentation\/iscp\/connection\/tag","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/tag"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/sendBaseTime(baseTime:persist:sendTimeout:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendBaseTime"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseTime"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4iSCP8BaseTimeV","kind":"typeIdentifier","text":"BaseTime"},{"kind":"text","text":", "},{"kind":"externalParam","text":"persist"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sendTimeout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ())?)"}],"role":"symbol","url":"\/documentation\/iscp\/connection\/sendbasetime(basetime:persist:sendtimeout:completion:)","title":"sendBaseTime(baseTime:persist:sendTimeout:completion:)","type":"topic","kind":"symbol","abstract":[{"text":"基準時刻を送信します。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/sendBaseTime(baseTime:persist:sendTimeout:completion:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/DEFAULT_AUTO_RECONNECT":{"type":"topic","abstract":[{"type":"text","text":"自動で再接続するかどうかのデフォルト値。"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_AUTO_RECONNECT"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","url":"\/documentation\/iscp\/connection\/default_auto_reconnect","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_AUTO_RECONNECT","title":"DEFAULT_AUTO_RECONNECT"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/sendCall(upstreamCall:sendTimeout:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendCall"},{"kind":"text","text":"("},{"kind":"externalParam","text":"upstreamCall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP12UpstreamCallV","text":"UpstreamCall"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sendTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ())?) -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/iscp\/connection\/sendcall(upstreamcall:sendtimeout:completion:)","title":"sendCall(upstreamCall:sendTimeout:completion:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"E2Eコールを送信します。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/sendCall(upstreamCall:sendTimeout:completion:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/DEFAULT_RECONNECT_MAX_INTERVAL":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_RECONNECT_MAX_INTERVAL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"role":"symbol","url":"\/documentation\/iscp\/connection\/default_reconnect_max_interval","kind":"symbol","type":"topic","title":"DEFAULT_RECONNECT_MAX_INTERVAL","abstract":[{"text":"自動で再接続する際の、リトライ間隔の最大値のデフォルト値。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_RECONNECT_MAX_INTERVAL"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/projectUUID":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"projectUUID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","url":"\/documentation\/iscp\/connection\/projectuuid","title":"projectUUID","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"プロジェクトID。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/projectUUID"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/connectTimeout":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"connectTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"url":"\/documentation\/iscp\/connection\/connecttimeout","title":"connectTimeout","kind":"symbol","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/connectTimeout","abstract":[{"type":"text","text":"コネクトのタイムアウト。"}]},"doc://jp.co.aptpod.iSCP/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/SQ"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/DEFAULT_PING_INTERVAL":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_PING_INTERVAL"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"role":"symbol","url":"\/documentation\/iscp\/connection\/default_ping_interval","title":"DEFAULT_PING_INTERVAL","type":"topic","kind":"symbol","abstract":[{"text":"Pingを送信する間隔のデフォルト値。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_PING_INTERVAL"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/isReconnecting":{"title":"isReconnecting","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isReconnecting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"再接続中かどうか。"}],"url":"\/documentation\/iscp\/connection\/isreconnecting","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/isReconnecting"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/pingInterval":{"title":"pingInterval","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pingInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"type":"topic","role":"symbol","abstract":[{"text":"Ping間隔。","type":"text"}],"url":"\/documentation\/iscp\/connection\/pinginterval","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/pingInterval"},"doc://jp.co.aptpod.iSCP/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/s7CVarArgP","title":"Swift.CVarArg"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/isConnecting":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isConnecting"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/iscp\/connection\/isconnecting","title":"isConnecting","kind":"symbol","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/isConnecting","abstract":[{"text":"実際にコネクションが接続中かどうか。","type":"text"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/address":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"address"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","url":"\/documentation\/iscp\/connection\/address","title":"address","type":"topic","kind":"symbol","abstract":[{"text":"接続先のアドレス。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/address"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/DEFAULT_ENCODING":{"kind":"symbol","title":"DEFAULT_ENCODING","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DEFAULT_ENCODING","kind":"identifier"},{"text":": ","kind":"text"},{"text":"EncodingName","preciseIdentifier":"s:4iSCP12EncodingNameO","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"エンコーディング名のデフォルト値。"}],"url":"\/documentation\/iscp\/connection\/default_encoding","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_ENCODING"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/connector":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"connector"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4iSCP10IConnectorP","kind":"typeIdentifier","text":"IConnector"}],"role":"symbol","url":"\/documentation\/iscp\/connection\/connector","title":"connector","kind":"symbol","type":"topic","abstract":[{"text":"トランスポートのコネクター。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/connector"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/connect(address:connector:tokenSource:nodeID:projectUUID:connectTimeout:pingTimeout:pingInterval:autoReconnect:reconnectBaseInterval:reconnectMaxInterval:encoding:delegate:e2eCallDelegate:completion:)":{"type":"topic","abstract":[{"type":"text","text":"iSCPで接続します。"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IConnector","preciseIdentifier":"s:4iSCP10IConnectorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tokenSource"},{"kind":"text","text":": ((("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> ()) -> ()), "},{"kind":"externalParam","text":"nodeID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"projectUUID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectTimeout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pingTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pingInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoReconnect"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reconnectBaseInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reconnectMaxInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encoding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EncodingName","preciseIdentifier":"s:4iSCP12EncodingNameO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4iSCP18ConnectionDelegateP","kind":"typeIdentifier","text":"ConnectionDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"e2eCallDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConnectionE2ECallDelegate","preciseIdentifier":"s:4iSCP25ConnectionE2ECallDelegateP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Connection","preciseIdentifier":"c:@M@iSCP@objc(cs)Connection"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ()))"}],"kind":"symbol","url":"\/documentation\/iscp\/connection\/connect(address:connector:tokensource:nodeid:projectuuid:connecttimeout:pingtimeout:pinginterval:autoreconnect:reconnectbaseinterval:reconnectmaxinterval:encoding:delegate:e2ecalldelegate:completion:)","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/connect(address:connector:tokenSource:nodeID:projectUUID:connectTimeout:pingTimeout:pingInterval:autoReconnect:reconnectBaseInterval:reconnectMaxInterval:encoding:delegate:e2eCallDelegate:completion:)","title":"connect(address:connector:tokenSource:nodeID:projectUUID:connectTimeout:pingTimeout:pingInterval:autoReconnect:reconnectBaseInterval:reconnectMaxInterval:encoding:delegate:e2eCallDelegate:completion:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/delegate":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4iSCP18ConnectionDelegateP","kind":"typeIdentifier","text":"ConnectionDelegate"},{"kind":"text","text":"?"}],"url":"\/documentation\/iscp\/connection\/delegate","title":"delegate","kind":"symbol","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/delegate","abstract":[{"type":"text","text":"コネクションで扱われるデリゲート。"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/nodeID":{"type":"topic","abstract":[{"type":"text","text":"接続するノードID。"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nodeID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","url":"\/documentation\/iscp\/connection\/nodeid","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/nodeID","title":"nodeID"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/tokenSource":{"title":"tokenSource","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tokenSource","kind":"identifier"},{"text":": (((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"token","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) -> ()) -> ())"}],"type":"topic","role":"symbol","abstract":[{"text":"トークンソース。","type":"text"}],"url":"\/documentation\/iscp\/connection\/tokensource","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/tokenSource"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/ITransportDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ITransportDelegate"}],"role":"symbol","url":"\/documentation\/iscp\/itransportdelegate","title":"ITransportDelegate","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"トランスポートの処理イベントです。"}],"navigatorTitle":[{"kind":"identifier","text":"ITransportDelegate"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/ITransportDelegate"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/sendCallAndWaitReplyCall(upstreamCall:sendTimeout:waitTimeout:completion:)":{"kind":"symbol","title":"sendCallAndWaitReplyCall(upstreamCall:sendTimeout:waitTimeout:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendCallAndWaitReplyCall","kind":"identifier"},{"text":"(","kind":"text"},{"text":"upstreamCall","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UpstreamCall","preciseIdentifier":"s:4iSCP12UpstreamCallV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sendTimeout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"waitTimeout","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"downstreamReplyCall"},{"kind":"text","text":": "},{"text":"DownstreamReplyCall","preciseIdentifier":"s:4iSCP19DownstreamReplyCallV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ())) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"text":"E2Eコールを送信し、リプライコールを受信します。","type":"text"}],"url":"\/documentation\/iscp\/connection\/sendcallandwaitreplycall(upstreamcall:sendtimeout:waittimeout:completion:)","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/sendCallAndWaitReplyCall(upstreamCall:sendTimeout:waitTimeout:completion:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/connect(completion:)":{"title":"connect(completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ()))"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"iSCPで接続します。"}],"url":"\/documentation\/iscp\/connection\/connect(completion:)","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/connect(completion:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/reconnectBaseInterval":{"title":"reconnectBaseInterval","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"reconnectBaseInterval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"自動で再接続する際の、リトライ間隔の初期値。"}],"url":"\/documentation\/iscp\/connection\/reconnectbaseinterval","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/reconnectBaseInterval"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/isOpen":{"type":"topic","abstract":[{"type":"text","text":"接続処理中かどうか。"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isOpen","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/iscp\/connection\/isopen","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/isOpen","title":"isOpen"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/reopenDownstream(_:completion:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reopenDownstream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Downstream","preciseIdentifier":"c:@M@iSCP@objc(cs)Downstream"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"downstream","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Downstream","preciseIdentifier":"c:@M@iSCP@objc(cs)Downstream"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> ()))"}],"url":"\/documentation\/iscp\/connection\/reopendownstream(_:completion:)","title":"reopenDownstream(_:completion:)","kind":"symbol","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/reopenDownstream(_:completion:)","abstract":[{"type":"text","text":"ストリーム設定を引き継いで別ストリームとして再度ダウンストリームを開きます。"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/DEFAULT_E2E_CALL_TIMEOUT":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_E2E_CALL_TIMEOUT"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"title":"DEFAULT_E2E_CALL_TIMEOUT","kind":"symbol","role":"symbol","url":"\/documentation\/iscp\/connection\/default_e2e_call_timeout","abstract":[{"text":"E2Eコールのタイムアウトのデフォルト値。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_E2E_CALL_TIMEOUT","type":"topic"},"doc://jp.co.aptpod.iSCP/s8CopyableP":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://jp.co.aptpod.iSCP/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/objc(cs)NSObject","title":"NSObject"},"doc://jp.co.aptpod.iSCP/s9EscapableP":{"type":"unresolvable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/s9EscapableP","title":"Swift.Escapable"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/DEFAULT_SEND_METADATA_TIMEOUT":{"title":"DEFAULT_SEND_METADATA_TIMEOUT","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"DEFAULT_SEND_METADATA_TIMEOUT","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"メタデータ送信のタイムアウトのデフォルト値。"}],"url":"\/documentation\/iscp\/connection\/default_send_metadata_timeout","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_SEND_METADATA_TIMEOUT"},"doc://jp.co.aptpod.iSCP/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection":{"navigatorTitle":[{"kind":"identifier","text":"Connection"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Connection"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/connection","title":"Connection","abstract":[{"type":"text","text":"iSCPのコネクションを表すクラスです。"}],"kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/sendCallAndWaitReplayCall(upstreamCall:sendTimeout:waitTimeout:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendCallAndWaitReplayCall"},{"kind":"text","text":"("},{"kind":"externalParam","text":"upstreamCall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UpstreamCall","preciseIdentifier":"s:4iSCP12UpstreamCallV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sendTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"waitTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"downstreamReplyCall"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4iSCP19DownstreamReplyCallV","kind":"typeIdentifier","text":"DownstreamReplyCall"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ())) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/iscp\/connection\/sendcallandwaitreplaycall(upstreamcall:sendtimeout:waittimeout:completion:)","title":"sendCallAndWaitReplayCall(upstreamCall:sendTimeout:waitTimeout:completion:)","type":"topic","kind":"symbol","deprecated":true,"abstract":[],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/sendCallAndWaitReplayCall(upstreamCall:sendTimeout:waitTimeout:completion:)"},"doc://jp.co.aptpod.iSCP/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/sendReplyCall(upstreamReplyCall:sendTimeout:completion:)":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/sendReplyCall(upstreamReplyCall:sendTimeout:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendReplyCall","kind":"identifier"},{"text":"(","kind":"text"},{"text":"upstreamReplyCall","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:4iSCP17UpstreamReplyCallV","text":"UpstreamReplyCall","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sendTimeout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ())?) -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/connection\/sendreplycall(upstreamreplycall:sendtimeout:completion:)","title":"sendReplyCall(upstreamReplyCall:sendTimeout:completion:)","abstract":[{"type":"text","text":"E2Eコールのリプライを送信します。"}],"kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/protocolVersion":{"kind":"symbol","title":"protocolVersion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"protocolVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"プロトコルバージョン。"}],"url":"\/documentation\/iscp\/connection\/protocolversion","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/protocolVersion"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/DEFAULT_PING_TIMEOUT":{"kind":"symbol","title":"DEFAULT_PING_TIMEOUT","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DEFAULT_PING_TIMEOUT","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Pingタイムアウトのデフォルト値。"}],"url":"\/documentation\/iscp\/connection\/default_ping_timeout","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/DEFAULT_PING_TIMEOUT"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"type":"topic","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","url":"\/documentation\/iscp","kind":"symbol","role":"collection"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/openUpstream(sessionID:expiryInterval:dataIDs:qos:ackInterval:persist:flushPolicy:openTimeout:closeTimeout:completion:)":{"type":"topic","abstract":[{"type":"text","text":"アップストリームを開きます。"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openUpstream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expiryInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dataIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP6DataIDV","text":"DataID"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"qos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP3QoSO","text":"QoS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ackInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"persist"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"flushPolicy"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4iSCP11FlushPolicyV","kind":"typeIdentifier","text":"FlushPolicy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"openTimeout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"closeTimeout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"upstream"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@iSCP@objc(cs)Upstream","kind":"typeIdentifier","text":"Upstream"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ()))"}],"kind":"symbol","url":"\/documentation\/iscp\/connection\/openupstream(sessionid:expiryinterval:dataids:qos:ackinterval:persist:flushpolicy:opentimeout:closetimeout:completion:)","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/openUpstream(sessionID:expiryInterval:dataIDs:qos:ackInterval:persist:flushPolicy:openTimeout:closeTimeout:completion:)","title":"openUpstream(sessionID:expiryInterval:dataIDs:qos:ackInterval:persist:flushPolicy:openTimeout:closeTimeout:completion:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/reconnectMaxInterval":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnectMaxInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"role":"symbol","url":"\/documentation\/iscp\/connection\/reconnectmaxinterval","title":"reconnectMaxInterval","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"自動で再接続する際の、リトライ間隔の最大値。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/reconnectMaxInterval"},"doc://jp.co.aptpod.iSCP/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/s28CustomDebugStringConvertibleP"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/e2eCallDelegate":{"title":"e2eCallDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"e2eCallDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4iSCP25ConnectionE2ECallDelegateP","kind":"typeIdentifier","text":"ConnectionE2ECallDelegate"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","abstract":[{"text":"E2Eコールのデリゲート。","type":"text"}],"url":"\/documentation\/iscp\/connection\/e2ecalldelegate","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/e2eCallDelegate"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection/pingTimeout":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"pingTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol","title":"pingTimeout","role":"symbol","url":"\/documentation\/iscp\/connection\/pingtimeout","abstract":[{"type":"text","text":"Pingタイムアウト。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection\/pingTimeout","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Connection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Connection"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Connection"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/objc(cs)NSObject"],"title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Connection"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/title","value":"Connection"},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/fragments","value":[{"kind":"identifier","text":"Connection"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/navigatorTitle","value":[{"kind":"identifier","text":"Connection"}]}]}]}