{"sections":[],"topicSections":[{"anchor":"Structures","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State"],"title":"Structures"},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/ackInterval","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/closeTimeout","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/connection","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/delegate","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/expiryInterval","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/filters","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/hash","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/id","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/omitEmptyChunk","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/openTimeout","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/qos","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/serverTime"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/close(completion:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/getState()","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/isEqual(_:)"],"title":"Instance Methods"},{"anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/DEFAULT_ACK_INTERVAL","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/DEFAULT_CLOSE_TIMEOUT","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/DEFAULT_EXPIRY_INTERVAL","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/DEFAULT_OMIT_EMPTY_CHUNK","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/DEFAULT_OPEN_TIMEOUT","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/DEFAULT_QOS"],"title":"Type Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/objc(pl)NSObject","doc:\/\/jp.co.aptpod.iSCP\/s7CVarArgP","doc:\/\/jp.co.aptpod.iSCP\/s28CustomDebugStringConvertibleP","doc:\/\/jp.co.aptpod.iSCP\/s23CustomStringConvertibleP","doc:\/\/jp.co.aptpod.iSCP\/SQ","doc:\/\/jp.co.aptpod.iSCP\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"identifier":{"url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Downstream","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/iscp\/downstream"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/iscp\/downstream"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"ダウンストリームを表すクラスです。","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP"]]},"metadata":{"navigatorTitle":[{"text":"Downstream","kind":"identifier"}],"symbolKind":"class","title":"Downstream","role":"symbol","roleHeading":"Class","modules":[{"name":"iSCP"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Downstream"}],"externalID":"c:@M@iSCP@objc(cs)Downstream"},"kind":"symbol","references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/ackInterval":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ackInterval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"title":"ackInterval","role":"symbol","type":"topic","url":"\/documentation\/iscp\/downstream\/ackinterval","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/ackInterval","abstract":[{"text":"Ack返却間隔。","type":"text"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/expiryInterval":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/expiryInterval","abstract":[{"type":"text","text":"有効期限。"}],"title":"expiryInterval","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/iscp\/downstream\/expiryinterval","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiryInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/connection":{"url":"\/documentation\/iscp\/downstream\/connection","role":"symbol","abstract":[{"text":"コネクション。","type":"text"}],"kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/connection","title":"connection","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Connection","preciseIdentifier":"c:@M@iSCP@objc(cs)Connection","kind":"typeIdentifier"}],"type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"title":"iSCP","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","url":"\/documentation\/iscp","type":"topic","kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/DEFAULT_EXPIRY_INTERVAL":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_EXPIRY_INTERVAL"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"title":"DEFAULT_EXPIRY_INTERVAL","url":"\/documentation\/iscp\/downstream\/default_expiry_interval","abstract":[{"text":"有効期限のデフォルト値。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/DEFAULT_EXPIRY_INTERVAL","role":"symbol","kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/filters":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"filters","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DownstreamFilter","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP16DownstreamFilterV"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/filters","url":"\/documentation\/iscp\/downstream\/filters","kind":"symbol","role":"symbol","title":"filters","type":"topic","abstract":[{"type":"text","text":"ダウンストリームフィルター。"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[],"title":"isEqual(_:)","url":"\/documentation\/iscp\/downstream\/isequal(_:)","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/id":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"}],"url":"\/documentation\/iscp\/downstream\/id","abstract":[{"text":"ストリームID。","type":"text"}],"kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/id","type":"topic","title":"id","role":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/getState()":{"role":"symbol","abstract":[{"type":"text","text":"ダウンストリームの状態を取得します。"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getState","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"State","preciseIdentifier":"s:4iSCP10DownstreamC5StateV","kind":"typeIdentifier"}],"title":"getState()","url":"\/documentation\/iscp\/downstream\/getstate()","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/getState()","kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/hash":{"kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/hash","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"type":"topic","url":"\/documentation\/iscp\/downstream\/hash","title":"hash","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/openTimeout":{"url":"\/documentation\/iscp\/downstream\/opentimeout","kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/openTimeout","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"openTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"text":"オープンのタイムアウト。","type":"text"}],"title":"openTimeout"},"doc://jp.co.aptpod.iSCP/objc(pl)NSObject":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/delegate":{"type":"topic","title":"delegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DownstreamDelegate","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP18DownstreamDelegateP"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"ダウンストリームで扱われるデリゲートです。"}],"url":"\/documentation\/iscp\/downstream\/delegate","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/delegate","kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/DEFAULT_CLOSE_TIMEOUT":{"title":"DEFAULT_CLOSE_TIMEOUT","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/DEFAULT_CLOSE_TIMEOUT","role":"symbol","type":"topic","url":"\/documentation\/iscp\/downstream\/default_close_timeout","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DEFAULT_CLOSE_TIMEOUT","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"クローズのタイムアウトのデフォルト値。"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/qos":{"title":"qos","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"qos"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4iSCP3QoSO","kind":"typeIdentifier","text":"QoS"}],"url":"\/documentation\/iscp\/downstream\/qos","abstract":[{"type":"text","text":"QoS。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/qos","role":"symbol"},"doc://jp.co.aptpod.iSCP/SQ":{"type":"unresolvable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/SQ","title":"Swift.Equatable"},"doc://jp.co.aptpod.iSCP/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://jp.co.aptpod.iSCP/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/closeTimeout":{"abstract":[{"type":"text","text":"クローズのタイムアウト。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/closeTimeout","kind":"symbol","title":"closeTimeout","type":"topic","role":"symbol","url":"\/documentation\/iscp\/downstream\/closetimeout","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream","role":"symbol","url":"\/documentation\/iscp\/downstream","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Downstream","kind":"identifier"}],"title":"Downstream","kind":"symbol","abstract":[{"type":"text","text":"ダウンストリームを表すクラスです。"}],"navigatorTitle":[{"text":"Downstream","kind":"identifier"}],"type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/close(completion:)":{"type":"topic","title":"close(completion:)","url":"\/documentation\/iscp\/downstream\/close(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"close"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> ())?)"}],"abstract":[{"type":"text","text":"ダウンストリームを閉じます。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/close(completion:)","kind":"symbol","role":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/DEFAULT_OMIT_EMPTY_CHUNK":{"abstract":[{"type":"text","text":"空チャンク省略フラグのデフォルト値。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/DEFAULT_OMIT_EMPTY_CHUNK","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/iscp\/downstream\/default_omit_empty_chunk","title":"DEFAULT_OMIT_EMPTY_CHUNK","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_OMIT_EMPTY_CHUNK"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://jp.co.aptpod.iSCP/SH":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/DEFAULT_QOS":{"role":"symbol","abstract":[{"text":"QoSのデフォルト値。","type":"text"}],"title":"DEFAULT_QOS","url":"\/documentation\/iscp\/downstream\/default_qos","kind":"symbol","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/DEFAULT_QOS","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DEFAULT_QOS","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QoS","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP3QoSO"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/DEFAULT_ACK_INTERVAL":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DEFAULT_ACK_INTERVAL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"kind":"symbol","type":"topic","url":"\/documentation\/iscp\/downstream\/default_ack_interval","title":"DEFAULT_ACK_INTERVAL","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/DEFAULT_ACK_INTERVAL","abstract":[{"type":"text","text":"Ack返却間隔のデフォルト値。"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/State":{"url":"\/documentation\/iscp\/downstream\/state","title":"Downstream.State","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/State","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"ダウンストリームの状態を表します。"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"navigatorTitle":[{"kind":"identifier","text":"State"}],"type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/serverTime":{"abstract":[{"type":"text","text":"サーバー時刻。"}],"url":"\/documentation\/iscp\/downstream\/servertime","title":"serverTime","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"role":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/serverTime"},"doc://jp.co.aptpod.iSCP/objc(cs)NSObject":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/DEFAULT_OPEN_TIMEOUT":{"type":"topic","role":"symbol","kind":"symbol","title":"DEFAULT_OPEN_TIMEOUT","abstract":[{"text":"オープンのタイムアウトのデフォルト値。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/DEFAULT_OPEN_TIMEOUT","url":"\/documentation\/iscp\/downstream\/default_open_timeout","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_OPEN_TIMEOUT"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Downstream/omitEmptyChunk":{"abstract":[{"type":"text","text":"空チャンク省略フラグ。"}],"kind":"symbol","url":"\/documentation\/iscp\/downstream\/omitemptychunk","title":"omitEmptyChunk","role":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/omitEmptyChunk","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"omitEmptyChunk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://jp.co.aptpod.iSCP/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"Downstream","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"Downstream","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"Downstream","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/hash"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Downstream\/isEqual(_:)"]}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Downstream","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream~1isEqual(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream~1isEqual(_:)\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream~1hash\/fragments"},{"value":"Downstream","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/title"},{"value":[{"kind":"identifier","text":"Downstream"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/fragments"},{"value":[{"text":"Downstream","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Downstream\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}