{"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP"]]},"identifier":{"url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/iscpVersionString","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iscpVersionString"},{"kind":"text","text":": <<error type>>"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"externalID":"c:@iscpVersionString","symbolKind":"var","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"iscpVersionString"},{"text":": <<error type>>","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"iscpVersionString"}],"roleHeading":"Global Variable","role":"symbol","title":"iscpVersionString","modules":[{"name":"iSCP"}]},"abstract":[{"type":"text","text":"Project version string for iscp"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscp\/iscpversionstring"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iscp\/iscpversionstring"]}],"sections":[],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"kind":"symbol","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"url":"\/documentation\/iscp","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/iscpVersionString":{"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iscpVersionString"},{"text":": <<error type>>","kind":"text"}],"role":"symbol","url":"\/documentation\/iscp\/iscpversionstring","kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/iscpVersionString","title":"iscpVersionString","navigatorTitle":[{"kind":"identifier","text":"iscpVersionString"}],"abstract":[{"text":"Project version string for iscp","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"iscpVersionString"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"iscpVersionString"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:c","text":"unsigned char"},{"kind":"text","text":" "},{"text":"iscpVersionString","kind":"identifier"},{"kind":"text","text":"[];"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1iscpVersionString\/title","op":"replace","value":"iscpVersionString"},{"value":[{"kind":"identifier","text":"iscpVersionString"}],"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1iscpVersionString\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}