{"abstract":[{"text":"アップストリームを表すクラスです。","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Upstream","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscp\/upstream"]},{"paths":["\/documentation\/iscp\/upstream"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","modules":[{"name":"iSCP"}],"title":"Upstream","externalID":"c:@M@iSCP@objc(cs)Upstream","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"Upstream"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Upstream"}],"roleHeading":"Class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP"]]},"topicSections":[{"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/State"],"title":"Structures"},{"title":"Instance Properties","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/ackInterval","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/closeTimeout","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/connection","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/delegate","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/expiryInterval","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/flushPolicy","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/hash","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/id","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/persist","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/qos","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/serverTime","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/sessionID"]},{"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/close(closeSession:completion:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/flush()","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/getState()","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/isEqual(_:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/writeDataPoint(dataID:dataPoint:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/writeDataPoints(dataID:dataPoints:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/writeDataPoints(dataPointGroup:)","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/writeDataPoints(dataPointGroups:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/DEFAULT_ACK_INTERVAL","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/DEFAULT_CLOSE_TIMEOUT","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/DEFAULT_EXPIRY_INTERVAL","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/DEFAULT_FLUSH_POLICY","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/DEFAULT_PERSIST","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/DEFAULT_QOS"],"title":"Type Properties"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/objc(pl)NSObject","doc:\/\/jp.co.aptpod.iSCP\/s7CVarArgP","doc:\/\/jp.co.aptpod.iSCP\/s28CustomDebugStringConvertibleP","doc:\/\/jp.co.aptpod.iSCP\/s23CustomStringConvertibleP","doc:\/\/jp.co.aptpod.iSCP\/SQ","doc:\/\/jp.co.aptpod.iSCP\/SH"],"kind":"relationships","title":"Conforms To"}],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/writeDataPoint(dataID:dataPoint:)":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/writeDataPoint(dataID:dataPoint:)","role":"symbol","abstract":[{"type":"text","text":"データポイントを送信バッファへ書き込みます。"}],"type":"topic","title":"writeDataPoint(dataID:dataPoint:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeDataPoint"},{"kind":"text","text":"("},{"text":"dataID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP6DataIDV","text":"DataID"},{"text":", ","kind":"text"},{"text":"dataPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DataPoint","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP9DataPointV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?"}],"url":"\/documentation\/iscp\/upstream\/writedatapoint(dataid:datapoint:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/writeDataPoints(dataPointGroups:)":{"title":"writeDataPoints(dataPointGroups:)","url":"\/documentation\/iscp\/upstream\/writedatapoints(datapointgroups:)","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/writeDataPoints(dataPointGroups:)","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"複数のデータポイントを送信バッファへ書き込みます。","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"writeDataPoints"},{"text":"(","kind":"text"},{"text":"dataPointGroups","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:4iSCP14DataPointGroupV","text":"DataPointGroup","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/DEFAULT_ACK_INTERVAL":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DEFAULT_ACK_INTERVAL","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"url":"\/documentation\/iscp\/upstream\/default_ack_interval","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Ack返却間隔のデフォルト値。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/DEFAULT_ACK_INTERVAL","title":"DEFAULT_ACK_INTERVAL"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/State":{"kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/State","abstract":[{"text":"アップストリームの状態を表します。","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"State"}],"title":"Upstream.State","type":"topic","url":"\/documentation\/iscp\/upstream\/state","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"State"}]},"doc://jp.co.aptpod.iSCP/objc(cs)NSObject":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/DEFAULT_FLUSH_POLICY":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DEFAULT_FLUSH_POLICY","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FlushPolicy","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP11FlushPolicyV"}],"url":"\/documentation\/iscp\/upstream\/default_flush_policy","kind":"symbol","abstract":[{"text":"データポイントのフラッシュポリシーのデフォルト値。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/DEFAULT_FLUSH_POLICY","type":"topic","title":"DEFAULT_FLUSH_POLICY","role":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/DEFAULT_EXPIRY_INTERVAL":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"DEFAULT_EXPIRY_INTERVAL","kind":"identifier"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"有効期限のデフォルト値。"}],"role":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/DEFAULT_EXPIRY_INTERVAL","title":"DEFAULT_EXPIRY_INTERVAL","kind":"symbol","url":"\/documentation\/iscp\/upstream\/default_expiry_interval"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/id":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"}],"url":"\/documentation\/iscp\/upstream\/id","kind":"symbol","abstract":[{"text":"ストリームID。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/id","type":"topic","title":"id","role":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/persist":{"abstract":[{"type":"text","text":"永続化するかどうか。"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"persist","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/persist","role":"symbol","type":"topic","title":"persist","url":"\/documentation\/iscp\/upstream\/persist"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/closeTimeout":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/closeTimeout","url":"\/documentation\/iscp\/upstream\/closetimeout","abstract":[{"text":"クローズのタイムアウト。","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closeTimeout","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"title":"closeTimeout","kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/expiryInterval":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/expiryInterval","type":"topic","abstract":[{"type":"text","text":"有効期限。"}],"url":"\/documentation\/iscp\/upstream\/expiryinterval","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"expiryInterval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"title":"expiryInterval","kind":"symbol"},"doc://jp.co.aptpod.iSCP/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/objc(pl)NSObject","type":"unresolvable"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/DEFAULT_CLOSE_TIMEOUT":{"abstract":[{"text":"クローズのタイムアウトのデフォルト値。","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_CLOSE_TIMEOUT"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/DEFAULT_CLOSE_TIMEOUT","role":"symbol","title":"DEFAULT_CLOSE_TIMEOUT","type":"topic","url":"\/documentation\/iscp\/upstream\/default_close_timeout"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/DEFAULT_PERSIST":{"type":"topic","abstract":[{"text":"永続化するかどうかのデフォルト値。","type":"text"}],"title":"DEFAULT_PERSIST","kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/DEFAULT_PERSIST","url":"\/documentation\/iscp\/upstream\/default_persist","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DEFAULT_PERSIST","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/hash":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/iscp\/upstream\/hash","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"hash","kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/DEFAULT_QOS":{"role":"symbol","url":"\/documentation\/iscp\/upstream\/default_qos","title":"DEFAULT_QOS","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/DEFAULT_QOS","abstract":[{"type":"text","text":"QoSのデフォルト値。"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DEFAULT_QOS"},{"text":": ","kind":"text"},{"text":"QoS","preciseIdentifier":"s:4iSCP3QoSO","kind":"typeIdentifier"}],"kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/ackInterval":{"type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/ackInterval","role":"symbol","abstract":[{"type":"text","text":"Ack返却間隔。"}],"title":"ackInterval","url":"\/documentation\/iscp\/upstream\/ackinterval","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ackInterval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/flush()":{"url":"\/documentation\/iscp\/upstream\/flush()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"flush"},{"text":"() -> ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"データポイントを手動でフラッシュします。"}],"role":"symbol","title":"flush()","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/flush()","kind":"symbol","type":"topic"},"doc://jp.co.aptpod.iSCP/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/s28CustomDebugStringConvertibleP"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/flushPolicy":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/flushPolicy","type":"topic","abstract":[{"text":"　データポイントのフラッシュポリシー。","type":"text"}],"url":"\/documentation\/iscp\/upstream\/flushpolicy","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"flushPolicy"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:4iSCP11FlushPolicyV","text":"FlushPolicy","kind":"typeIdentifier"}],"title":"flushPolicy","kind":"symbol"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/qos":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"qos","kind":"identifier"},{"kind":"text","text":": "},{"text":"QoS","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP3QoSO"}],"title":"qos","kind":"symbol","type":"topic","url":"\/documentation\/iscp\/upstream\/qos","abstract":[{"type":"text","text":"QoS。"}],"role":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/qos"},"doc://jp.co.aptpod.iSCP/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/s23CustomStringConvertibleP"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream":{"abstract":[{"text":"アップストリームを表すクラスです。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","kind":"symbol","url":"\/documentation\/iscp\/upstream","role":"symbol","type":"topic","title":"Upstream","navigatorTitle":[{"kind":"identifier","text":"Upstream"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Upstream"}]},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/writeDataPoints(dataPointGroup:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"writeDataPoints","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dataPointGroup"},{"text":": ","kind":"text"},{"text":"DataPointGroup","kind":"typeIdentifier","preciseIdentifier":"s:4iSCP14DataPointGroupV"},{"text":") -> ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"writeDataPoints(dataPointGroup:)","kind":"symbol","type":"topic","url":"\/documentation\/iscp\/upstream\/writedatapoints(datapointgroup:)","abstract":[{"type":"text","text":"複数のデータポイントを送信バッファへ書き込みます。"}],"role":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/writeDataPoints(dataPointGroup:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/sessionID":{"abstract":[{"type":"text","text":"セッションID。"}],"title":"sessionID","url":"\/documentation\/iscp\/upstream\/sessionid","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/sessionID","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"sessionID","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol"},"doc://jp.co.aptpod.iSCP/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/s7CVarArgP"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/delegate":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP16UpstreamDelegateP","text":"UpstreamDelegate"},{"text":"?","kind":"text"}],"title":"delegate","kind":"symbol","type":"topic","url":"\/documentation\/iscp\/upstream\/delegate","abstract":[{"type":"text","text":"アップストリームで扱われるデリゲート。"}],"role":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/delegate"},"doc://jp.co.aptpod.iSCP/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/jp.co.aptpod.iSCP\/SQ"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/writeDataPoints(dataID:dataPoints:)":{"title":"writeDataPoints(dataID:dataPoints:)","abstract":[{"text":"複数のデータポイントを送信バッファへ書き込みます。","type":"text"}],"url":"\/documentation\/iscp\/upstream\/writedatapoints(dataid:datapoints:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"writeDataPoints"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dataID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:4iSCP6DataIDV","kind":"typeIdentifier","text":"DataID"},{"kind":"text","text":", "},{"text":"dataPoints","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DataPoint","preciseIdentifier":"s:4iSCP9DataPointV"},{"text":"]) -> ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/writeDataPoints(dataID:dataPoints:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","kind":"symbol","url":"\/documentation\/iscp","role":"collection","type":"topic","title":"iSCP"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/serverTime":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"serverTime","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"サーバー時刻。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/serverTime","type":"topic","title":"serverTime","role":"symbol","url":"\/documentation\/iscp\/upstream\/servertime"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/connection":{"title":"connection","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"connection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@iSCP@objc(cs)Connection","text":"Connection","kind":"typeIdentifier"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/connection","url":"\/documentation\/iscp\/upstream\/connection","role":"symbol","abstract":[{"text":"コネクション。","type":"text"}],"kind":"symbol","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/getState()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getState","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP8UpstreamC5StateV","text":"State"}],"role":"symbol","title":"getState()","kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/getState()","url":"\/documentation\/iscp\/upstream\/getstate()","abstract":[{"type":"text","text":"アップストリームの状態を取得します。"}],"type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual(_:)","kind":"symbol","url":"\/documentation\/iscp\/upstream\/isequal(_:)","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/isEqual(_:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/close(closeSession:completion:)":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/close(closeSession:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"close","kind":"identifier"},{"kind":"text","text":"("},{"text":"closeSession","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ())?)","kind":"text"}],"url":"\/documentation\/iscp\/upstream\/close(closesession:completion:)","abstract":[{"type":"text","text":"アップストリームを閉じます。"}],"title":"close(closeSession:completion:)","kind":"symbol","role":"symbol","type":"topic"},"doc://jp.co.aptpod.iSCP/SH":{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"Upstream"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"Upstream","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"Upstream","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/hash"]},{"title":"Instance Methods","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/isEqual(_:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/jp.co.aptpod.iSCP\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Upstream"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream~1hash\/title","value":"hash"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream~1hash\/fragments"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/title","value":"Upstream","op":"replace"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/fragments","value":[{"text":"Upstream","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace"}]}]}