{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscp\/upstream\/connection"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connection"},{"text":": ","kind":"text"},{"text":"Connection","kind":"typeIdentifier","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","preciseIdentifier":"c:@M@iSCP@objc(cs)Connection"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream"]]},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connection"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@iSCP@objc(cs)Connection","text":"Connection"}],"roleHeading":"Instance Property","title":"connection","symbolKind":"property","externalID":"s:4iSCP8UpstreamC10connectionAA10ConnectionCvp","role":"symbol","modules":[{"name":"iSCP"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"text":"コネクション。","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/connection"},"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream":{"abstract":[{"type":"text","text":"アップストリームを表すクラスです。"}],"navigatorTitle":[{"text":"Upstream","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","url":"\/documentation\/iscp\/upstream","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Upstream"}],"kind":"symbol","title":"Upstream"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"kind":"symbol","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"url":"\/documentation\/iscp","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/connection":{"abstract":[{"text":"コネクション。","type":"text"}],"kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/connection","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"connection","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@iSCP@objc(cs)Connection","text":"Connection","kind":"typeIdentifier"}],"url":"\/documentation\/iscp\/upstream\/connection","role":"symbol","type":"topic","title":"connection"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Connection":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Connection","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Connection","url":"\/documentation\/iscp\/connection","title":"Connection","abstract":[{"text":"iSCPのコネクションを表すクラスです。","type":"text"}],"navigatorTitle":[{"text":"Connection","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Upstream","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/title"},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/fragments","value":[{"kind":"identifier","text":"Upstream"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/navigatorTitle","value":[{"text":"Upstream","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/title","value":"Connection"},{"op":"replace","value":[{"kind":"identifier","text":"Connection"}],"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/fragments"},{"value":[{"kind":"identifier","text":"Connection"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Connection\/navigatorTitle"}]}]}