{"variants":[{"paths":["\/documentation\/iscp\/upstream\/default_ack_interval"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"DEFAULT_ACK_INTERVAL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Ack返却間隔のデフォルト値。","type":"text"}],"sections":[],"metadata":{"roleHeading":"Type Property","modules":[{"name":"iSCP"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DEFAULT_ACK_INTERVAL"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"title":"DEFAULT_ACK_INTERVAL","externalID":"s:4iSCP8UpstreamC20DEFAULT_ACK_INTERVALSdvpZ"},"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream"]]},"identifier":{"url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/DEFAULT_ACK_INTERVAL","interfaceLanguage":"swift"},"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"kind":"symbol","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"url":"\/documentation\/iscp","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream":{"abstract":[{"type":"text","text":"アップストリームを表すクラスです。"}],"navigatorTitle":[{"text":"Upstream","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","url":"\/documentation\/iscp\/upstream","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Upstream"}],"kind":"symbol","title":"Upstream"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/DEFAULT_ACK_INTERVAL":{"title":"DEFAULT_ACK_INTERVAL","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_ACK_INTERVAL"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"url":"\/documentation\/iscp\/upstream\/default_ack_interval","abstract":[{"text":"Ack返却間隔のデフォルト値。","type":"text"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/DEFAULT_ACK_INTERVAL","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/title","value":"Upstream"},{"value":[{"text":"Upstream","kind":"identifier"}],"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Upstream"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/navigatorTitle"}]}]}