{"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream"]]},"identifier":{"url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/delegate","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamDelegate","preciseIdentifier":"s:4iSCP16UpstreamDelegateP","text":"UpstreamDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/iscp\/upstream\/delegate"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"アップストリームで扱われるデリゲート。"}],"metadata":{"externalID":"s:4iSCP8UpstreamC8delegateAA0B8Delegate_pSgvp","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:4iSCP16UpstreamDelegateP","text":"UpstreamDelegate"},{"text":"?","kind":"text"}],"modules":[{"name":"iSCP"}],"roleHeading":"Instance Property","title":"delegate"},"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"kind":"symbol","role":"collection","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"url":"\/documentation\/iscp","type":"topic"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/delegate":{"role":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/delegate","type":"topic","kind":"symbol","url":"\/documentation\/iscp\/upstream\/delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:4iSCP16UpstreamDelegateP","text":"UpstreamDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"text":"アップストリームで扱われるデリゲート。","type":"text"}],"title":"delegate"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream":{"abstract":[{"type":"text","text":"アップストリームを表すクラスです。"}],"navigatorTitle":[{"text":"Upstream","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","url":"\/documentation\/iscp\/upstream","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Upstream"}],"kind":"symbol","title":"Upstream"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/UpstreamDelegate":{"type":"topic","role":"symbol","identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/UpstreamDelegate","title":"UpstreamDelegate","kind":"symbol","url":"\/documentation\/iscp\/upstreamdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UpstreamDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"UpstreamDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"アップストリームで扱われるデリゲートです。"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/title","op":"replace","value":"Upstream"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/fragments","op":"replace","value":[{"kind":"identifier","text":"Upstream"}]},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Upstream"}]}]}]}