{"variants":[{"paths":["\/documentation\/iscp\/upstream\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iscp\/upstream\/isequal(_:)"]}],"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","externalID":"c:@M@iSCP@objc(cs)Upstream(im)isEqual:","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"modules":[{"name":"iSCP"}],"symbolKind":"method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream"]]},"identifier":{"url":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/isEqual(_:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/iscp\/upstream\/isequal(_:)","title":"isEqual(_:)","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream\/isEqual(_:)"},"doc://jp.co.aptpod.iSCP/documentation/iSCP":{"type":"topic","abstract":[{"type":"text","text":"iSCP Client for Swift は、iSCP version 2 を用いたリアルタイムAPIにアクセスするためのクライアントライブラリです。"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP","title":"iSCP","url":"\/documentation\/iscp","kind":"symbol","role":"collection"},"doc://jp.co.aptpod.iSCP/documentation/iSCP/Upstream":{"navigatorTitle":[{"kind":"identifier","text":"Upstream"}],"identifier":"doc:\/\/jp.co.aptpod.iSCP\/documentation\/iSCP\/Upstream","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Upstream"}],"role":"symbol","type":"topic","url":"\/documentation\/iscp\/upstream","kind":"symbol","title":"Upstream","abstract":[{"text":"アップストリームを表すクラスです。","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"isEqual:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isEqual:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream~1isEqual(_:)\/fragments"},{"value":"Upstream","op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/title"},{"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/fragments","value":[{"text":"Upstream","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"Upstream"}],"op":"replace","path":"\/references\/doc:~1~1jp.co.aptpod.iSCP~1documentation~1iSCP~1Upstream\/navigatorTitle"}]}]}